### ISSUE TITLE
Unable to install on latest Node and NPM releases

### ISSUE THREAD

**Issue by antgonzales** [sindresorhus/gulp-imagemin#102]
I received the following errors when I tried to run `npm install --save-dev gulp-imagemin`:

```
npm WARN optional dep failed, continuing imagemin-pngquant@4.0.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
npm ERR! cb() never called!
```

node v0.10.36
npm v2.7.0

**Comment by sindresorhus** [comment]
https://www.google.com/search?q=npm+WARN+optional+dep+failed%2C+continuing+imagemin-pngquant&oq=npm+WARN+optional+dep+failed%2C+continuing+imagemin-pngquant&aqs=chrome..69i57j69i64l3.1892j0j1&sourceid=chrome&es_sm=91&ie=UTF-8
