### ISSUE TITLE
npm install often stucks on jpegtran/pngquant/gifsicle/optipng postinstalls

### ISSUE THREAD

**Issue by gsklee** [sindresorhus/gulp-imagemin#105]
I hope there are some ways to opt to not installing some of these upon `npm install`... is it possible?

**Comment by kevva** [comment]
They are already optional as seen [here](https://github.com/imagemin/imagemin/blob/master/package.json#L48-L53). If the installation get stuck it's probably related to https://github.com/imagemin/imagemin/issues/68.
