### ISSUE TITLE
unmet dependencies...

### ISSUE THREAD

**Issue by davidbarrows** [sindresorhus/gulp-imagemin#109]
I'm having similar issues to one logged previously, as shown here; any thoughts or advice would be appreciated.  My impression is, gulp-imagemin is not getting installed correctly even though these are only warnings and not errors.  

Thanks,
Dave

davids-mbp:dBWeb3 davidwbarrows$ sudo npm install gulp-imagemin --save-dev
npm WARN package.json gulp-filelog@0.4.1 No README data
\
> gifsicle@2.0.1 postinstall /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs/node_modules/chalk/node_modules/has-ansi requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs/node_modules/chalk/node_modules/has-ansi requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-unzip/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs/node_modules/chalk/node_modules/has-ansi requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs/node_modules/chalk/node_modules/has-ansi requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-unzip/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs/node_modules/chalk/node_modules/has-ansi requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress-unzip/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/got requires read-all-stream@'^2.0.0' but will load
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb3/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/read-all-stream,
npm WARN unmet dependency which is version 1.0.2
gulp-imagemin@2.2.1 node_modules/gulp-imagemin
├── object-assign@2.0.0
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.1.1, through2@0.6.5, vinyl@0.4.6, dateformat@1.0.11, lodash.template@3.5.1, multipipe@0.1.2)
└── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.3, stream-combiner@0.2.1, through2@0.6.5, concat-stream@1.4.8, vinyl@0.4.6, meow@2.1.0, vinyl-fs@0.3.13, imagemin-svgo@4.1.2, imagemin-gifsicle@4.1.0)
davids-mbp:dBWeb3 davidwbarrows$ sudo npm uninstall gulp-imagemin --save-dev
unbuild gulp-imagemin@2.2.1
davids-mbp:dBWeb3 davidwbarrows$

**Comment by kevva** [comment]
As you pointed out, these are only warnings and will not have an impact.
