### ISSUE TITLE
Disable logging at the end when verbose is false

### ISSUE THREAD

**Issue by Skyrpex** [sindresorhus/gulp-imagemin#112]
Hi!

The plugin currently logs the minification details when the task is done. This is OK, but I thought it would be nice if that feature could be switched off using configuration options.

```
[15:07:31] gulp-imagemin: Minified 14 images (saved 10.24 kB - 29.9%)
```

Regards,

**Comment by kevva** [comment]
Well, no. Most users expect some sort of information. We already disable a lot of logging when the `verbose` option is `false`.
