### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by fbm-static** [sindresorhus/gulp-imagemin#114]
This is in relation of this issue: https://github.com/gulpjs/gulp/issues/1044#issuecomment-103123018

**Comment by elijahwww** [comment]
thanks fbm-static, I was about to post it here myself, but you beat me to it.

**Comment by kevva** [comment]
Yup, it's pretty slow at the moment but it's getting fixed.

**Comment by shinnn** [comment]
According to [this `require` time analysis](https://github.com/gulpjs/gulp/issues/1044#issuecomment-135860605), `imagemin`'s startup time has been sufficiently improved.
