### ISSUE TITLE
gulp-imagemin is ineffective at compressing .jpg files

### ISSUE THREAD

**Issue by ltarasiewicz** [sindresorhus/gulp-imagemin#116]
Hello,

I've used this configuration with `gulp-imagemin`:

    gulp.task('compress', function () {
        return gulp.src('themes/myTheme/images/*')
            .pipe(imagemin({
                progressive: true,
                optimizationLevel: 7,
                svgoPlugins: [{removeViewBox: false}],
                use: [pngquant(), jpegtran(), optipng(), gifsicle()]
            }))
            .pipe(gulp.dest('themes/myTheme/images/dist'));
    });

Unfortunately, jpg files that weigh ~300kb got rot reduced by ~10kb which I believe is not effective at all. This is regardless of the `optimizationLevel` setting. 

I tried to save the same image as 'optimizaed for web' with GIMP, and it got reduced by ~50% in size.
Is my configuration wrong? How can I get `gulp-imagemin` to achieve similar results to GIMP/Photoshop at compressing jpg files?

**Comment by sindresorhus** [comment]
The bundled plugins are lossless. Try any of the lossy jpeg plugins: https://www.npmjs.com/browse/keyword/imageminplugin

**Comment by dcdeiv** [comment]
I have the same issue. 0.02% of compression is just ridiculous. https://compressor.io/ does better.

**Comment by KayakinKoder** [comment]
@dcdeiv you didn't read or understand sindresorhus' comment. The default compress algorithms that are packaged with imagemin are *lossless*, meaning they are designed, on purpose, to not lose any quality. Thus the very little compression you see by default. Using the plugins he linked to you can compress in a *lossy* manner, meaning you can get highly compressed files.

As an example, using the mozjpeg plugin set at `quality: 50`, a 12 MB .jpeg image was compressed to 883 kb:

```
const gulp = require('gulp');
const imagemin = require('gulp-imagemin');
const imageminMozjpeg = require('imagemin-mozjpeg'); 

gulp.task('default', function() {
    return gulp.src(['src/**/*'])
        .pipe(imagemin([
            imageminMozjpeg({
                quality: 50
            })
        ]))
        .pipe(gulp.dest('dist'));
});
```

**Comment by blakeaross** [comment]
@KayakinKoder I think @dcdeiv may still be correct. Imageoptim is freeware that I use on Mac, and it compresses JPGs losslessly. I was just experimenting with using this gulp plugin, and a lossless compression via Imageoptim just compressed an 84kb image down to 67kb. If I attempt lossless compression via gulp-imagemin, it merely reduces the same image from 84kb to 81kb. It appears to me that imagemin does lossless compression poorly in comparison with the lossless compression of free Imageoptim software.
