### ISSUE TITLE
Vendor folder for imagemin-optipng failes to download on Windows 10

### ISSUE THREAD

**Issue by JimiC** [sindresorhus/gulp-imagemin#118]
I'm a long time `ASP.NET` developer and recently I dived into `ASP.NET 5` discovering `bower` and `npm`.
While playing around with `Gulp` and getting a grip on the tool I stumbled upon an issue with `gulp-imagemin` that had me fiddling around for hours.
While I was trying to make it work for some `PNG` files, I was constantly getting the following error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```
When I installed `imagemin-optipng` and replaced the usage of `gulp-imagemin` in the gulpfile I finally had it running. So, out of curiosity, I started drilling into the installation folders of both packages to spot any diffs.
When I reached the `optipng-bin`, there it was. `vendor` folder was missing from the `gulp-imagemin` package. As soon as I copied the vendor folder from the `imagemin-optipng` package to the `gulp-imagemin` one and replaced back the usage of the `gulp-imagemin` in the gulpfile, everything fell in place and run as they supposed to.

I don't know if this qualifies as an issue for `gulp-imagemin` or it's an `npm` issue, never the less I decided to post it here anyways. Hope my finding can be of some use.

Edit: Here are some additional info I found, although I now believe that this issue belongs to https://github.com/imagemin/optipng-bin

> optipng-bin@3.0.2 postinstall C:\Users\Jimi\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js
  ‼ Command failed: 'C:\Users\Jimi\documents\visual' is not recognized as an internal or external command,
operable program or batch file.
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: ./configure --with-system-zlib --prefix="C:\Users\Jimi\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="C:\Users\Jimi\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" && make install
Command failed: '.' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
imagemin-optipng@4.3.0 node_modules\imagemin-optipng
├── is-png@1.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── exec-buffer@2.0.1 (tempfile@1.1.1)
└── optipng-bin@3.0.2 (logalot@2.1.0, bin-build@2.1.1, bin-wrapper@3.0.1)

Note that the the words `visual studio 2015` have no underscores but whitespaces.

Edit 2:
I finally figured out what is causing the issue. 
```npm WARN engine imagemin@3.2.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"v0.12.4","npm":"1.4.9"})```
VS 2015 RC has npm version 1.4.9, the package requires a version >=2.1.5 which is the source of my troubles. Unfortunately I haven't yet found a way to successfully update npm to the latest version (nope installing Node.js doesn't update npm for VS).

**Comment by MarkAPhillips** [comment]
In relation to updating NPM you can do the following:

```
Run "cmd.exe" as administrator

> npm update npm -g

which installs npm in the following directory

C:\Users\<my-username>\AppData\Roaming\npm\node_modules\npm\

if the above npm directory does not exist then run:

>npm install npm -g

this should install npm globally

copy contents of npm to the npm folder in 

C:\Program Files\nodejs\node_modules\npm\
```

Node was using an outdated version of npm a while back (this may have changed) and had to run the above to be able to update npm directly.

**Comment by kevva** [comment]
Just tried installing on Windows and it worked perfectly.

```sh
$ npm i optipng-bin
-
> optipng-bin@3.0.2 postinstall c:\Users\kevva\Projects\test\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully
```

Try updating `npm` and report back.

**Comment by JimiC** [comment]
@MarkAPhillips Doesn't help as the ASP.NET 5 project also looks in the projects node_modules folder in order for the gulp tasks to run and this overrides the global installation of npm.

@kevva Was it on Windows 10 with VS2015 RC and a ASP.NET 5 project?

**Comment by aaronroberson** [comment]
Is this related to [npm issue 8682)(https://github.com/npm/npm/issues/8682), [bin build issue 6](https://github.com/kevva/bin-build/issues/6) and [download issue 64](kevva/download#64)? I tried downgrading [bin-build](https://github.com/kevva/bin-build/issues/6) from 2.1.2 to 2.1.1 and I was able to do an `npm install` once, but subsequent attempts are failing. As you can see from optipng-bin [post install script](https://github.com/imagemin/optipng-bin/blob/master/lib/install.js), the package is trying to fetch OptiPNG from sourceforge and and is failing.

**Comment by YinshawnRao** [comment]
Error: Cannot find module 'imagemin-optipng'   

shall I install individually ?

**Comment by jonespen** [comment]
A PATH variable solution would be great. We're having trouble installing imagemin-gifsicle, imagemin-jpegtran and imagemin-optipng due to a corporate proxy (from hell), and have to manually download the binary files.

**Comment by davidhutson** [comment]
If you are like me behind a corporate firewall then all traffic is routed through the proxy server. Here is what has worked for me in the past. Most tools need to be explicitly setup to pass proxy credentials otherwise you will get 407 proxy timeouts errors, unless you use fiddler you probably will not see these errors and wonder what the hells going on. 

For the following programs, all files should be saved inside C:\Users\ [USERNAME]

Use a program like Sublime Text to save the files as they all must start with a (.) extension.

Atom
Create a file called .apmrc
https-proxy=http://yourproxyserver:port
proxy=http://yourproxyserver:port
strict-ssl = false

Bower
Create a file called .bowerrc
{
  "proxy": "http://yourproxyserver:port",
  "https-proxy": "http://yourproxyserver:port",
  "strict-ssl": false
}

NPM
Create a file called .npmrc
proxy=http://yourproxyserver:port
https-proxy=http://yourproxyserver:port

*If you fancy an alternative node package manager to npm then I would recommend IED https://github.com/alexanderGugel/ied is pretty awesome

Git
Create a file called .gitconfig and add this on to the end.

[http]
	proxy = http://yourproxyserver:port
[https]
	proxy = http://yourproxyserver:port

I hope this helps someone.
