### ISSUE TITLE
It's making images larger?

### ISSUE THREAD

**Issue by Jakobud** [sindresorhus/gulp-imagemin#119]
I have an image that is 47,336 bytes. After running through imagemin via gulp, the output is 49,190 bytes... I wasn't expecting this. I'm not using any options:

```
.pipe(imagemin())
```

Am I just misunderstanding something here? I was expecting a smaller file size. I have hundreds of similar images and it seems to be doing it to all of them. I'm using `2.2.1`.

**Comment by kevva** [comment]
That's strange. We're using the original image if the optimized one is larger.

**Comment by Jakobud** [comment]
Well obviously yeah I need to use the original image, but we are setting up an automated system that will run thousands of files through this optimization every day. I guess we were just expecting the output to always be smaller. I guess I have to write a test to see if the output was actually smaller or not??

**Comment by kevva** [comment]
What happens if you re-install imagemin? Does the binaries install correctly or do you get any errors?

**Comment by Jakobud** [comment]
Actually we found the problem. We were piping the image through `gulp-image-resize` (but not actually resizing it in this case) and it was outputting the JPEG with zero compression, thus making it slightly larger. That was the problem. Disregard this. Thanks!

**Comment by namntdnc** [comment]
hello world
