### ISSUE TITLE
Caching the result

### ISSUE THREAD

**Issue by ansman** [sindresorhus/gulp-imagemin#121]
It would be nice if the result of the optimization could be cached so that next time the cached version could be used instead of optimizing it again.

**Comment by sindresorhus** [comment]
Use a cache gulp plugin: https://github.com/gulpjs/gulp#incremental-builds

**Comment by ansman** [comment]
I was talking about an on disk cache but point taken, it would be done with a separate plugin.

**Comment by sindresorhus** [comment]
More here: https://www.npmjs.com/search?q=gulp+cache

Like: https://www.npmjs.com/package/gulp-file-cache
