### ISSUE TITLE
events.js:72: throw er; // Unhandled 'error' event, Error: spawn ENOENT again

### ISSUE THREAD

**Issue by piupiupiu** [sindresorhus/gulp-imagemin#125]
Hello,

I have exactly the same issue which was already discussed here many times but ONLY with GIF images.

    log('Compressing and copying images');

        return gulp
            .src(config.images)
            .pipe(plugins.imagemin({optimizationLevel: 4}))
            .pipe(gulp.dest(config.tmp + 'images'))

Config.images has the following value:

     images: [client + 'images/**/*.png', client + 'images/**/*.jpg', client + 'images/**/*.jpeg', client +     'images/**/*.svg', client + 'images/**/*.gif'],

This happens with any gif image. I also tried to specifed one exact path to exact gif image. The same error occured. The images of the other formats are processed fine.

What could be the reason of the problem?

**Comment by diegorodriguesvieira** [comment]
I have this same error...

**Comment by gabrielgomesferraz** [comment]
I have this same error...

**Comment by Perchework** [comment]
+1

**Comment by thehindenburg** [comment]
+1

**Comment by tomieric** [comment]
OS:win10
node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\vendor

The 'jpegtran.exe' is gone!

**Comment by comeontom** [comment]
+1

**Comment by yaboo777** [comment]
+1

**Comment by orta-sanz** [comment]
+1

**Comment by shinnn** [comment]
Should be reported to https://github.com/sindresorhus/gulp-imagemin/issues/125 *in detail* (more example code, or a small repository that can reproduce the problem).
