### ISSUE TITLE
Console log doesn't tell me which files are optimised

### ISSUE THREAD

**Issue by darrenhaken** [sindresorhus/gulp-imagemin#129]
When using gulp-imagemin it printed out to the console which files it optimised and by how much.
However I've just ran it again and it's only telling me the number of files optimised and the total saving.

Is this a feature change or am I doing something wrong?

**Comment by sindresorhus** [comment]
Duplicate of #108.

**Comment by darrenhaken** [comment]
Thanks! Strange I don't recall having to use --verbose last time.
Has this been changed in the package?

I appreciate the speedy response!
