### ISSUE TITLE
npm install --save-dev gulp-imagemin requires administrator access on Windows.

### ISSUE THREAD

**Issue by kmh3785** [sindresorhus/gulp-imagemin#130]
Installing gulp-imagemin requires administrator access on Windows.

- Windows 7
- npm v2.11.3
- Node v0.12.7

![nodeerror](https://cloud.githubusercontent.com/assets/5419324/9796424/54b0039c-57b3-11e5-91da-db3954eb0010.PNG)

This error does not occur when the Node command prompt is run as an administrator. It also only occurs on the first run of installation. Meaning, once I get the error, if I run install gulp-imagemin a second time, it works without a problem.

Any idea what would cause it to break on the first run?

**Comment by sindresorhus** [comment]
npm support → https://github.com/npm/npm/issues
