### ISSUE TITLE
npm install --save-dev gulp-imagemin

### ISSUE THREAD

**Issue by monkindey** [sindresorhus/gulp-imagemin#135]
### hi sindresorhus
today i want to compress the images for my repo ,and then input the `npm install --save-dev gulp-imagemin` use cmd in my repo path, and then appear something wrong!
![image](https://cloud.githubusercontent.com/assets/6913898/10098677/b237f9d0-63b5-11e5-9013-48bf3f607ae3.png)
can you help me look why the cmd doesn't work?

Thanks you !
my English is poor.

**Comment by shinnn** [comment]
That's not a gulp-imagemin issue actually.
