### ISSUE TITLE
Animated gif

### ISSUE THREAD

**Issue by bampakoa** [sindresorhus/gulp-imagemin#137]
Hi,

I am using gulp-imagemin and tried to compress an animated gif but it failed. Does it support the particular type of image?

I have reported the issue in **gifsicle** and **imagemin** repos but I did not have any luck to find what is the cause of the error.

Thanks

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum

Read this article again and again.

**Comment by shinnn** [comment]
Anyway we should add a test for animated GIF optimization to [imagemin-gifsicle](https://github.com/imagemin/imagemin-gifsicle).
