### ISSUE TITLE
cannot install gulp-imagemin on linux

### ISSUE THREAD

**Issue by Treagzhao** [sindresorhus/gulp-imagemin#138]
When i tried to install gulp-imagemin on linux,it said as

'✖ Error: ./configure --disable-shared --prefix="/root/DownLoad/ToumiPc/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/root/DownLoad/ToumiPc/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install'

and i cannot make it work at all,how can i do with it ?

**Comment by monkindey** [comment]
i think you use the https://registry.npm.taobao.org install? may be not sync

**Comment by shinnn** [comment]
That's not a gulp-imagemin issue actually.
