### ISSUE TITLE
Could we get a `quiet` or `silent` option?

### ISSUE THREAD

**Issue by ehgoodenough** [sindresorhus/gulp-imagemin#140]
As much as I like knowing how much my images were minified, my console is getting way too cluttered with `[21:37:05] gulp-imagemin: Minified 1 image (saved 3.38 kB - 83.6%)` and the like. Could we get an option to silence any `gutil.log`?

**Comment by ehgoodenough** [comment]
If it's in scope, it shouldn't be any more difficult than wrapping a couple of lines with a ``if(opts.silent)``

https://github.com/sindresorhus/gulp-imagemin/blob/master/index.js#L35
https://github.com/sindresorhus/gulp-imagemin/blob/master/index.js#L74
https://github.com/sindresorhus/gulp-imagemin/blob/master/index.js#L88

**Comment by sindresorhus** [comment]
Very soon. With gulp 4.0 (imminent release) we can use https://github.com/gulpjs/gulplog to choose the log level. I guess that message should be using the `info` level.

**Comment by ehgoodenough** [comment]
Oh, nice! Can't wait for 4.0. Thanks!

**Comment by sindresorhus** [comment]
I'll keep this open so I don't forget.

**Comment by DylanPiercey** [comment]
@sindresorhus doesn't it make sense to hide this log behind the `verbose` option anyway?

**Comment by FranciscoKnebel** [comment]
Started using this package now, and I have to agree with @DylanPiercey, logs should be behind the verbose option, no need to keep just one log.

**Comment by cruelbob** [comment]
+1

**Comment by olthof** [comment]
Since we have "verbose: false", should this issue now be closed?

**Comment by sindresorhus** [comment]
Closing as I'm not interested in adding more logging related options.
