### ISSUE TITLE
Flatten image before compression

### ISSUE THREAD

**Issue by barry205** [sindresorhus/gulp-imagemin#141]
Hi all

Is it possible to flatten one image, on top of all our images inside the images directory?

Example: I need to use photoshop to add a company logo on top of all the photos, though, from what I can gather, this is not possible using gulp-imagemin.

Is there a way to combine two images, somehow tell gulp we have a logo (another.png) to stick on top before we minimize our images?

Hope this makes sense, thanks.

**Comment by sindresorhus** [comment]
This plugin is image minification. What you're looking for should be a separate plugin. If you can't find something like that on the gulp search http://gulpjs.com/plugins/, feel free to open an request here: https://github.com/sindresorhus/module-requests

**Comment by barry205** [comment]
Cool, thanks for quick reply.
I'll check out the plugins, and thanks for the references.
