### ISSUE TITLE
jpegtran Build Fails ... 

### ISSUE THREAD

**Issue by simspace-dev** [sindresorhus/gulp-imagemin#148]
I get the following when I try to install gulp-imagemin, any ideas?
Thanks,
Chris

> jpegtran-bin@3.0.6 postinstall /Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `/Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin/vendor" --bindir="/Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin/vendor" --bindir="/Users/simspace/Webdev/learn-gulp/node_modules/jpegtran-bin/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by sindresorhus** [comment]
The error is coming from `jpegtran-bin`. So open an issue there instead.
