### ISSUE TITLE
Image min creates a folder which I have not specified and puts images into it but not in my destination folder specified. 

### ISSUE THREAD

**Issue by Yathi** [sindresorhus/gulp-imagemin#155]
Hi, I have a weird issue where my gulp-imagemin tasks copies my images into "img/" instead of putting the images into "dist/images" like I ask it to. 

Here is the part of the imagemin code in gulp file.js:

    gulp.task('imagemin', function() {
      return del(['dist/images']), gulp.src('app/images/**/*')
        .pipe(cache(imagemin({ optimizationLevel: 3, progressive: true, interlaced: true })))
        .pipe(gulp.dest('dist/images'))
        .pipe(notify({ message: 'Images task complete' }));
     });

Please let me know what is causing this issue. I am attaching my package.json and gulpfile.js.
[Archive.zip](https://github.com/sindresorhus/gulp-imagemin/files/104471/Archive.zip)

**Comment by shinnn** [comment]
@Yathi Your gulpfile includes a lot of unrelated stuff. Remove non-image tasks and plugins for easier review. Also there are no files under `app/images`.

**Comment by shinnn** [comment]
@sindresorhus ? Fixed?

**Comment by sindresorhus** [comment]
It's not an issue with this plugin. It doesn't work with the filessystem at all. That's all gulp. Probably something wrong in the gulpfile.
