### ISSUE TITLE
Empty combined SVG

### ISSUE THREAD

**Issue by markorosic** [sindresorhus/gulp-imagemin#156]
It seems that imagemin doesn't handle combined svg files right (used [svgstore](https://github.com/w0rm/gulp-svgstore) to create the file in question), resulting in almost empty svg file containing only `<svg xmlns="http://www.w3.org/2000/svg">` line.

**Comment by shinnn** [comment]
Issues with SVG parser and output go to https://github.com/svg/svgo. Clarify what "combined svg" is if you submit the issue there.
