### ISSUE TITLE
Crash on Xubuntu 14.04

### ISSUE THREAD

**Issue by Litarvan** [sindresorhus/gulp-imagemin#157]
I've got this :

[20:11:46] Starting 'minimize-images'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:988:11)
  at Process.ChildProcess._handle.onexit (child_process.js:779:34)

With this code :

return gulp.src(IMAGES_FOLDER + '/**/*.png')
        .pipe(imagemin())
        .pipe(gulp.dest(MINIMIZED_IMAGES_FOLDER));

If you could help me, thanks by advance

**Comment by sindresorhus** [comment]
That means something wrong happened when installing the `imagemin` dependency. Open an issue on: https://github.com/imagemin/imagemin
