### ISSUE TITLE
Able to compress jpg images except for the below image part 2

### ISSUE THREAD

**Issue by dmullings81** [sindresorhus/gulp-imagemin#158]
Much like the issue described here  #142  I am unable to compress the exact same jpeg, but with a different error code. The image is this one:
![pizzeria](https://cloud.githubusercontent.com/assets/13616405/12968434/3bac4cea-d0b5-11e5-96f7-19827c6d5f1c.jpg)

I am able to compress other jpegs.
I get the following error code in console:
`events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: write EOF
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)`

I tried altering the index.js as described by shinnn [here ](https://github.com/imagemin/imagemin-jpegtran/commit/c3d6626c7ec8948f9aab2dadd13269e8c54bfb16).
Many thanks

**Comment by shinnn** [comment]
Reinstall gulp-imagemin.

**Comment by dmullings81** [comment]
I tried that, and I received the same error. 
I then tried reinstalling jpegtran, still the same error.
Both installed with no error messages.

**Comment by shinnn** [comment]
At least this is not a gulp-imagemin issue but a imagemin-jpegtran one.

No need to open a new issue, just commit it [here](https://github.com/imagemin/imagemin-jpegtran/issues/8).

**Comment by dmullings81** [comment]
Thank you shinn. どうもありがとうございます。
