### ISSUE TITLE
Not working with imagemin-pngquant v5

### ISSUE THREAD

**Issue by idhamperdameian** [sindresorhus/gulp-imagemin#169]
gulp-imagemin seem not working with new version of imagemin-pngquant v5.

package.json
```
"devDependencies": {
    "gulp": "^3.9.1",
    "gulp-imagemin": "^2.4.0",
    "imagemin-pngquant": "^5.0.0"
  }
```

**Comment by idhamperdameian** [comment]
Duplicate #167
Solve with `npm install --save-dev imagemin-pngquant@4`

**Comment by tunaSandwich** [comment]
This did not work for me
