### ISSUE TITLE
Plugin/options usage example?

### ISSUE THREAD

**Issue by m-e-h** [sindresorhus/gulp-imagemin#172]
Could we get a more detailed example in the readme for using the bundled plugin options?
3.0 doesn't work with my previous `svgoPlugins:` configuration and I can't seem to correct it.

**Comment by kevva** [comment]
We've disabled the ability to override the default options. Install the plugins separately and define them like:

```js
.pipe(imagemin([imageminSvgo(opts), imageminOptipng(opts)]))
```

**Comment by sindresorhus** [comment]
I intended to write release notes, but been traveling, so didn't have the chance until now. This should make it clear: https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0

**Comment by sindresorhus** [comment]
I've also improved the imagemin-svgo readme: https://github.com/imagemin/imagemin-svgo/commit/e6db1b41cd043db87c40a448a99e5f45387625c1

**Comment by m-e-h** [comment]
Thanks guys. I see now. Sorry for the impatients.
