### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'kill' of undefined

### ISSUE THREAD

**Issue by TheLoneKing** [sindresorhus/gulp-imagemin#173]
My gulp-imagemin task is failing with the below error.

> [00:24:25] Starting 'imagemin'...
[00:24:25] Finished 'imagemin' after 50 ms
Unhandled rejection TypeError: Cannot read property 'kill' of undefined
    at module.exports (/media/theloneking/Technical/Learning/AngularJS/Exercise/myApp/node_modules/gulp-imagemin/node_modules/imagemin-optipng/node_modules/exec-buffer/node_modules/execa/index.js:80:24)
    at /media/theloneking/Technical/Learning/AngularJS/Exercise/myApp/node_modules/gulp-imagemin/node_modules/imagemin-optipng/node_modules/exec-buffer/index.js:31:15

I guess the problem is relating to imagemin-optipng plugin. How do I get past this?

**Comment by jlengstorf** [comment]
I just ran into this issue, and found that uninstalling/reinstalling `gulp-imagemin` solved the problem.

```
npm uninstall gulp-imagemin --save-dev
npm cache clean
npm install --save-dev gulp-imagemin
```

Cleaning the cache was important, because prior to that I did an uninstall/reinstall that didn't make a difference.

**Comment by TheLoneKing** [comment]
Thanks. Solved it!

**Comment by miguelsmuller** [comment]
The error continues in my task. I even doing this @jlengstorf

**Comment by jlengstorf** [comment]
@miguelsmuller I'm not sure I'll be much help beyond the fix listed above. Can you share the error output to make sure you're up against the same issue?

**Comment by miguelsmuller** [comment]
```[11:57:22] Using gulpfile /home/vagrant/projeto/gulpfile.js
[11:57:22] Starting 'imagemin'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'kill' of undefined
    at module.exports (/home/vagrant/projeto/node_modules/execa/index.js:80:24)
    at fsP.writeFile.then (/home/vagrant/projeto/node_modules/exec-buffer/index.js:31:15)```

**Comment by miguelsmuller** [comment]
I'm using a VM ubuntu ... I wanted a way to understand WHAT could be happening
is it dependence problem?

**Comment by miguelsmuller** [comment]
someone?

**Comment by codyrushing** [comment]
I am having the same issue as @miguelsmuller - any updates?

**Comment by miguelsmuller** [comment]
Nothing expensive. I've gone from page 10 of google with several different terms.
I believe it is my machine and not the package.
But I need a light repository contributors.

**Comment by codyrushing** [comment]
@miguelsmuller For me, this was a due to the fact that jpegtran could not be built properly.  For some reason, uninstalling and reinstalling NVM fixed this for me.

**Comment by listsssl** [comment]
I still see this error, after following the recommendation above.

I opened a new bug, #198 ,  but it was closed, simply referencing this bug's URL.  again.
