### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by lukepolo** [sindresorhus/gulp-imagemin#174]
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/vagrant/Code/LukePOLO/node_modules/gifsicle/vendor/gifsicle ENOENT

**Comment by kevva** [comment]
This should be opened at https://github.com/imagemin/gifsicle-bin. Preferably with some more info about what happened (logging etc.) upon installing this module.
