### ISSUE TITLE
No compression at all

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [sindresorhus/gulp-imagemin#176]
Soo This snippet below, used to give me considerable reduction in size and thus considerable compression in 2.4.0 with imagemin 4.0.0

> ```
> var $$ = require('gulp-load-plugins')
> var compressJpg = require('imagemin-jpeg-recompress')
> 
> gulp.src(images/**/*.{png,jpg})
> .pipe($$.if('*.jpg', $$.imagemin({
>             use: [
>                 compressJpg({
>                     //target quality for the recompressed jpg - 0.5 is 50% quality
>                     target: 0.5
>                 })
>             ]
>         })))
> ```

Now, with version 3 and imagemin v5, this does not have any impact at all

No compression at all.

I happened to read about overriding the default plugins  [here](https://github.com/sindresorhus/gulp-imagemin#plugins).
and thus
I have tried the below snippet for debugging what goes into and what come out of imagemin

> 
> ```
> var $$ = require('gulp-load-plugins')
> var compressJpg = require('imagemin-jpeg-recompress')
>var pngquant = require('imagemin-pngquant')
>
>(stuff from another plugin)
> .pipe($$.debug({title:'to imagemin-v3'}))
>  .pipe($$.imagemin([$$.imagemin.gifsicle(), compressJpg({target:0.5}), pngquant(), $$.imagemin.svgo()]))
>  .pipe($$.debug({title:'from imagemin-v3'}))
> ```

and 
I find that,
nothing is passed downstream by imagemin if I try to override the plugins.

**Comment by seamofreality** [comment]
Doesn't work for me either. It says it minified X images but the svgs for example are just the same as before. Worked for me with the version I used before (2.4.0).

**Comment by kevva** [comment]
@Nitin-Prabhakar, `imagemin-jpeg-recompress` hasn't been converted to the new API yet.

@seamofreality, could you share your config?

**Comment by shinnn** [comment]
No feedback after https://github.com/sindresorhus/gulp-imagemin/issues/176#issuecomment-218489849.
