### ISSUE TITLE
dyld: Library not loaded. Reason: image not found

### ISSUE THREAD

**Issue by SndrL** [sindresorhus/gulp-imagemin#179]
Since upgrading to version 3 i'm getting the following error **only on jpg** files:

`dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found`

Someone having the same issue? Or better: a fix? ;)

**Comment by kevva** [comment]
@sindresorhus, many users seem to have problems using `imagemin-mozjpeg`. Should we revert to using `imagemin-jpegtran` again maybe?

**Comment by sindresorhus** [comment]
@kevva Sure, let's do that for now until it's resolved.

**Comment by SndrL** [comment]
I just reverted back to 2.4.0 and it's ok now.
Reverting seems like a good idea :)

Any clue on why this is a problem for many users?

**Comment by kevva** [comment]
@SndrL, in previous versions we used `imagemin-jpegtran` for `jpg` compression. `mozjpeg` is a lot better, but seems to cause problems for some users.

**Comment by kevva** [comment]
This particular issue should be fixed in https://github.com/sindresorhus/gulp-imagemin/commit/bf8d84207b2f38c96ec5596da7d778047aa7ccc6 and in the next release.
