### ISSUE TITLE
Copy unsupported files instead of ignoring

### ISSUE THREAD

**Issue by rahul-desai3** [sindresorhus/gulp-imagemin#180]
Is there a configuration that I can do to achieve this?

**Comment by kevva** [comment]
Doesn't it already https://github.com/sindresorhus/gulp-imagemin/blob/master/index.js#L42-L48?

**Comment by rahul-desai3** [comment]
@kevva Unfortunately, it did not.

My code is similar to the one in the docs:

```
gulp.src('src/images/*') // also tried "src/images/**"
        .pipe(imagemin())
        .pipe(gulp.dest('build'))

**Comment by kevva** [comment]
That's weird. What file types doesn't get copied? We have a test for this https://github.com/sindresorhus/gulp-imagemin/blob/master/test.js#L40-L46 and it passes.

**Comment by rahul-desai3** [comment]
My apologies. Its working now. `jsHint` was terminating Gulp due to Javascript issues and that was breaking the imagemin task.

Thanks.
