### ISSUE TITLE
Error: Cannot find module 'imagemin-gifsicle'

### ISSUE THREAD

**Issue by rejas** [sindresorhus/gulp-imagemin#184]
With v3.0.0 I get this error running gulp (Error: Cannot find module 'imagemin-gifsicle') when calling gulp-imagemin with these options:
  {
    "optimizationLevel": 3,
    "progressive": true,
    "interlaced": true
  }
Shouldn't optionalDependencies be handled more gracefully or can I fix something on my side?

**Comment by kevva** [comment]
Try installing it manually. If you see any errors, report them on `gifsicle-bin` (check other issues before reporting).

**Comment by rejas** [comment]
I dont think it is a problem of gifsicle-bin but rather that those optionalDependencies (imagemin-gifsicle, imagemin-jpgtran etc) are not really optional in your code. According to https://docs.npmjs.com/files/package.json#optionaldependencies "It is still your program's responsibility to handle the lack of the dependency." I'll try to make a pull-request with some optional dep handling....

**Comment by kevva** [comment]
You can still override the default plugins. If `imagemin-giflsicle` fails, just do this:

```js
imagemin([
	imagemin.jpegtran(),
	imagemin.optipng(),
	imagemin.svgo()
]);
```
