### ISSUE TITLE
fixed Uncaught Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by littledu** [sindresorhus/gulp-imagemin#188]
Hi, when I was using gulp-imagemin in electron of windows, an error occured as `Uncaught Error: EPERM: operation not permitted, write. `

Here is what caused this issue:  https://github.com/electron/electron/issues/2033

Currently my solution is:

```javascript
try{
    gutil.log('gulp-imagemin:', msg);
}catch(err){
    console.log('gulp-imagemin:', msg);
}
```

Would you please solve this problem so that we can use it normally when reinstalled? 

Thanks.

**Comment by sindresorhus** [comment]
gulp-imagemin is supported on Node.js. You're free to run it elsewhere, like in Electron, but that's unsupported, so you're own your own.

**Comment by littledu** [comment]
OK
