### ISSUE TITLE
WARN: npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

### ISSUE THREAD

**Issue by diegosantamarta** [sindresorhus/gulp-imagemin#191]
When installing gulp-imagemin I'm getting this warning about a dependencie.

**Comment by sindresorhus** [comment]
It's just a warning.

**Comment by lquanyang** [comment]
Thanks

**Comment by hipertracker2** [comment]
It's not a warning. My  Ansible script fails because of that
``
failed: (item={'name': '@vue/cli'}) => {
    "changed": false,
    "cmd": "/bin/npm install --global ''",
    "invocation": {
        "module_args": {
            "executable": null,
            "global": true,
            "ignore_scripts": false,
            "name": "@vue/cli",
            "path": null,
            "production": false,
            "registry": null,
            "state": "latest",
            "version": "latest"
        }
    },
    "item": {
        "name": "@vue/cli"
    },
    "msg": "",
    "rc": 1,
    "stderr": "npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead\nnpm ERR! Unexpected token \u0000 in JSON at position 2080 while parsing near '....3.0\",\"dependencies\"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000...'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2019-02-26T15_14_20_728Z-debug.log\n",
    "stderr_lines": [
        "npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead",
        "npm ERR! Unexpected token \u0000 in JSON at position 2080 while parsing near '....3.0\",\"dependencies\"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000...'",
        "",
        "npm ERR! A complete log of this run can be found in:",
        "npm ERR!     /root/.npm/_logs/2019-02-26T15_14_20_728Z-debug.log"
    ],
    "stdout": "",
    "stdout_lines": []
}
``
