### ISSUE TITLE
imagemin-jpeg-recompress does't works

### ISSUE THREAD

**Issue by Vadizar** [sindresorhus/gulp-imagemin#193]
imagemin-jpeg-recompress does not work on gulp-imagemin 3.0.1

var
   gulp = require('gulp'),
   imagemin = require('gulp-imagemin'),
   imageminJR = require('imagemin-jpeg-recompress');

gulp.task('imagemin', function() {
   gulp.src('./img/**/*')
      .pipe(imagemin({
         use: [
            imageminJR({
               method: 'ms-ssim'
            })
         ]
      }))
      .pipe(gulp.dest('./public/img/'))
});

**Comment by shinnn** [comment]
Should be reported on https://github.com/imagemin/imagemin-jpeg-recompress. Also just saying "does not work" is almost the same as saying nothing. We need more detailed info (e.g. error message, Node version, image file).
