### ISSUE TITLE
Does the latest version not support node6.+?

### ISSUE THREAD

**Issue by cddsgtc** [sindresorhus/gulp-imagemin#195]
This is the task of copy
```
gulp.task('copy-image', function () {
    return gulp.src('image/*.{png,jpg,gif,ico}')
         .pipe(imagemin())
        .pipe(gulp.dest('dist/image'));
});
```
this is the task of watching 
```
gulp.watch('image/*.{png,jpg,gif,ico}',['copy-image']).on("change", reload);
```
**but the processing can't finish**
always is 
```
Starting 'copy-image'...
```

**Comment by shinnn** [comment]
@cddsgtc I couldn't confirm the problem. Please show us an error-reproducible repository.

**Comment by cddsgtc** [comment]
@shinnn ~~，What error-reproducible repository do you want to get, error-code? or some prompt words? I really want to help you to collect that ,but how?

**Comment by shinnn** [comment]
@cddsgtc A public Github repository with a `package.json`, `gulpfile` and some images, by which we can always reproduce the problem that you're running into with a simple `npm start` command.

**Comment by cddsgtc** [comment]
@shinnn https://github.com/cddsgtc/imageinIssues/tree/origin

**Comment by shinnn** [comment]
@cddsgtc I cannot reproduce the process hanging problem by your repository. Also, don't include a lot of unrelated stuff in the example repository.

Closing.

**Comment by cddsgtc** [comment]
@shinnn Maybe you are right, before yesterday,it works normally,
