### ISSUE TITLE
Level 3 images cannot be generated in the directory

### ISSUE THREAD

**Issue by decsev** [sindresorhus/gulp-imagemin#197]
Level 3 images cannot be generated in the directory, win7/node -v 4.4.2

**Comment by shinnn** [comment]
I guess you're talking about [`optimizationlevel`](https://github.com/imagemin/imagemin-optipng/tree/6bced1c795f51aa85cb270737e68ec108f061c4e#optimizationlevel) option but [it just works on Windows](https://ci.appveyor.com/project/ShinnosukeWatanabe/imagemin-optipng/build/job/5v8tm72vp11mcthk) even if [it defaults to `3`](https://github.com/imagemin/imagemin-optipng/commit/43bef00f3b4fb9c06881c53b020dece5d83c1c20). Anyway, don't use obsolete Windows 7. Just upgrade to Windows 10.

**Comment by decsev** [comment]
![171c tm](https://cloud.githubusercontent.com/assets/8290456/16942002/222f9216-4dc6-11e6-93e5-5f3e95c360da.png) , sorry, i mean that images can't be generated in this directory

**Comment by shinnn** [comment]
gulp-imagemin itself doesn't write files. If the problem really occurs, that is an issue with [vinyl-fs](https://www.npmjs.com/package/vinyl-fs).

**Comment by decsev** [comment]
thanks
