### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by verdond2** [sindresorhus/gulp-imagemin#202]
For some reason my svg files are getting completely stripped out. I was expecting just whitespace to be removed but it is completely removing everything. The files seem to display correctly but the issue arises when I am using svg sprites. Just wondering if there is a setting or option that I am missing when it comes to dealing with SVG. Just to clarify it seems to be stripping out 'symbol' elements

**Comment by sindresorhus** [comment]
This module use https://github.com/svg/svgo to do the actual SVG minification, so try asking there instead.
