### ISSUE TITLE
Valid Extensions

### ISSUE THREAD

**Issue by MasterOfZozo** [sindresorhus/gulp-imagemin#203]
gulp-imagemin filter drops all files except jpg, jpeg, png, gif, svg.
This is a problem when I want to use other formats.
e.g. [imagemin-webp](https://github.com/imagemin/imagemin-webp) for support of webp images.
Please, add support of more extensions or remove this filter. Webp is nice format.

**Comment by sindresorhus** [comment]
`imagemin-webp` converts jpg/png/gif images to webp.

**Comment by MasterOfZozo** [comment]
I think you don't understand me. As `gulp-imagemin` is wrapper around imagemin it should have same extensions. But when I add `imagemin-webp` it in my compression proccess through `gulp-imagemin` so it still do nothing. `index.js` succesfully add `imagemin-webp` plugin, but .webp files are returned with message Skipping unsupported image.

There is my build code:
```
"use strict";
let gulp = require("gulp"),
        changed = require("gulp-changed"),
        plumber = require("gulp-plumber"),
        imagemin = require("gulp-imagemin"),
        imageminWebp = require('imagemin-webp');

gulp.task("images", function (cb) {

  let plugins = [
    imagemin.gifsicle(),
    imagemin.jpegtran(),
    imagemin.optipng(),
    imagemin.svgo(),
    imageminWebp()];
  
  let options = {
    verbose: true
  };
  
  gulp.src("src/images/**/*")
          .pipe(plumber())
          .pipe(changed("dist/images/"))
          .pipe(imagemin(plugins, options))
          .pipe(gulp.dest("dist/images"));
});
```

**Comment by MasterOfZozo** [comment]
I have added pull request with changes. I'm sorry for conflict in branches. I am new in world of git.
