### ISSUE TITLE
gulp  task throws errors

### ISSUE THREAD

**Issue by smlombardi** [sindresorhus/gulp-imagemin#206]
First, a colleague go an error since I copied and pasted your gulp task not realizing it was ES6 and not vanilla ES5 js.  So I modified the task to be ES5.  I runs for me, but for my colleague the gulp file throws an error when run, even when that task is not being run.  Error screenshot attached.

I had to comment out the link to  `var imagemin = require('gulp-imagemin');` and the task for her to be able to run any gulp tasks.

![pasted image at 2016_08_15 02_59 pm](https://cloud.githubusercontent.com/assets/835148/17676273/c4015dbe-62fb-11e6-95cb-5bc6b6a9c4df.png)

**Comment by sindresorhus** [comment]
This module requires Node.js 4 or higher as defined in package.json: https://github.com/sindresorhus/gulp-imagemin/blob/cb12e3332dce75dd581a907bb80fa8ce4e61c183/package.json#L13

**Comment by smlombardi** [comment]
Some of my colleagues are stuck on Node 0.1.2 due to other projects. 

Is there any way to use this in my gulp file in a task that they simply will not run?  For example, I am the one responsible for builds.  So, I only included this task as part of my `gulp build` task.  Everyone else just runs `gulp` which does not include the imagemin task.

I'm confused as to why an error is thrown for people who are not actually running the `imagemin` task.
