### ISSUE TITLE
Help with compression plugin jpg

### ISSUE THREAD

**Issue by LynxDelli** [sindresorhus/gulp-imagemin#209]
Can someone be a bit more specific and give plugin and/or parameter for JPG to get better compression rate, target is 50% or more.

I looked at plugins - https://www.npmjs.com/browse/keyword/imageminplugin

var imageminJpegtran = require('imagemin-jpegtran');
var imageminMozjpeg = require('imagemin-mozjpeg');
var imageminJpegoptim = require('imagemin-jpegoptim');

and tried with any of above:

gulp.task('image_min', function () {
   gulp.src('./tests/original/**/*')
      .pipe(imagemin({
         use: [...()]
      }))
      .pipe(gulp.dest('./tests/compressed'));
});

gulp.task('default', ['image_min']);
but I always get 10.5% 

Point me if I'm doing something wrong.

**Comment by sindresorhus** [comment]
Set the `max` option in jpegoptim to do lossy compression. All of them are lossless by default, which results in less gain.
