### ISSUE TITLE
Possible EventEmitter memory leak detected & deprecated cross-spawn-async@2.2.4

### ISSUE THREAD

**Issue by carlafranca** [sindresorhus/gulp-imagemin#210]
on npm install I getting the following warns:

npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3916) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

Could you please let me know if there is a fix for this. 
Thanks

**Comment by carlafranca** [comment]
Just found this https://github.com/npm/npm/issues/13656

**Comment by kevva** [comment]
Yup, not an issue with this module.
