### ISSUE TITLE
Optional Dependencies aren't actually optional

### ISSUE THREAD

**Issue by 321ckatz123** [sindresorhus/gulp-imagemin#216]
These require calls are at the top of the file and cannot be excluded due to this. As such, they should either be made to be required when actually used or switched to not be optional (as you can specify npm install to not install optional dependencies).

const imageminGifsicle = require('imagemin-gifsicle');
const imageminJpegtran = require('imagemin-jpegtran');
const imageminOptipng = require('imagemin-optipng');
const imageminSvgo = require('imagemin-svgo');

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-imagemin/pull/185#issuecomment-221079692
