### ISSUE TITLE
PNG compression is lossy by default

### ISSUE THREAD

**Issue by svivian** [sindresorhus/gulp-imagemin#218]
Not sure if this is the best repo to submit the issue, so let me know if there's a better palce for this.

If you have PNG images with alpha transparency, calling imagemin on them is actually lossy, not lossless. The default for optipng has `colorTypeReduction: true` but with alpha transparency images, this reduces it to a 1-bit alpha layer.

Example: I took the first Facebook icon from here: https://icons8.com/web-app/for/color/facebook

Here's a zoomed in view of the original image (left) and the imagemin one (right). You can see it loses the soft edge.

![imagemin](https://cloud.githubusercontent.com/assets/207887/19225088/95ec6cbe-8e8b-11e6-8236-58820393ab22.png)

Not sure exactly what the best solution is - using `colorTypeReduction: false` by default would be good, but then it won't reduce colours on flat images (without alpha).

**Comment by sindresorhus** [comment]
That's weird. OptiPNG touts itself as being lossless.

> A lossless transform of a PNG image file is a transform which fully preserves the rendered RGB triples (the RGB triples that come either directly, or from a palette index, or from a gray->RGB expansion), **the rendered transparency** (the alpha samples that come either directly, or from a tRNS chunk, or the implicit 100% opacity assumed due to the lack of any explicit transparency information), the order of rendering (sequential or interlaced), and the semantics contained by the ancillary chunks. - http://optipng.sourceforge.net/pngtech/optipng.html

**Comment by svivian** [comment]
"Rendered transparency" in your quote most likely refers to when there are more than 256 colours and the alpha loss doesn't occur. It only happens when the colours are reduced. Same happens in in GIMP too - reducing the above image to 256 colours removes the alpha transparency.

**Comment by Kakurady** [comment]
@svivian Hi, did you check the image transparency in GIMP? GIMP doesn't support PNGs with indexed color _and_ 8-bit transparency (it was created when indexed color meant GIFs), but most browsers (and Inkscape) do.
![comparison](https://user-images.githubusercontent.com/138435/32500963-c9ac958e-c3a4-11e7-8e2b-5c9bec51ab8c.PNG)

Try opening the image in a browser, and see if it still happens?

**Comment by svivian** [comment]
Sorry for the delay. Checked into this and you're right, it's a problem with GIMP.
