### ISSUE TITLE
Configured optional dependencies are not optional

### ISSUE THREAD

**Issue by thasmo** [sindresorhus/gulp-imagemin#221]
Installing `gulp-imagemin` using `yarn` fails - for some reason - to install the optional dependencies, which results in this error when running `gulp`:
```
Error: Cannot find module 'imagemin-jpegtran'
```

This happens probably because the optional dependencies are [required](https://github.com/sindresorhus/gulp-imagemin/blob/v3.0.3/index.js#L8-L11) nonetheless.

`npm`'s documentation states the following regarding optional dependencies:
```
It is still your program's responsibility to handle the lack of the dependency. ...
```

**Comment by thasmo** [comment]
Just found a [related issue](https://github.com/yarnpkg/yarn/issues/628).

**Comment by sindresorhus** [comment]
Sure. PR welcome. Weird that it works with npm though.

**Comment by ekryski** [comment]
I'm actually having this with NPM as well.

**Comment by ekryski** [comment]
@sindresorhus how do you want to handle it? Just make them regular dependencies?

**Comment by michelecocuccio** [comment]
Yeah having the same problem here using NPM :(

**Comment by DevanB** [comment]
Same issue here. Seems to be gifsicle being the problem for me.

**Comment by rejas** [comment]
I am really baffled about this thread. Especially that @sindresorhus writes "Weird that it works with npm though." when this PR exists for month: https://github.com/sindresorhus/gulp-imagemin/pull/185
Now I am wondering what I should have done differently to get this through or heard like this thread....
