### ISSUE TITLE
gulp-imagemin install fails on windows 8

### ISSUE THREAD

**Issue by Kristories** [sindresorhus/gulp-imagemin#23]
``` cli
> pngquant-bin@0.1.7 postinstall path\node_modules\gulp-imagemin\node_modules\image-min\node_modules\pngquant-bin
> node index.js

✓ pre-build test passed successfully

> gifsicle@0.1.5 postinstall path\node_modules\gulp-imagemin\node_modules\image-min\node_modules\gifsicle
> node index.js

✓ pre-build test passed successfully

> jpegtran-bin@0.2.6 postinstall path\node_modules\gulp-imagemin\node_modules\image-min\node_modules\jpegtran-bin
> node index.js

✗ building is not supported on win32
```

Same issue with `grunt-contrib-imagemin`
https://github.com/gruntjs/grunt-contrib-imagemin/issues/109

**Comment by sina-mirhejazi** [comment]
I checked jpegtran-bin issues and find this
[jepgtran-bin issue](https://github.com/imagemin/jpegtran-bin/issues/54)

that end up solving the problem, but gulp version of it still not working
I guess you should upgrade dependency version so we can download it automated.
