### ISSUE TITLE
cpu up to 100%

### ISSUE THREAD

**Issue by crazyduker** [sindresorhus/gulp-imagemin#234]
cpu up to 100% when there is too many images.

**Comment by sindresorhus** [comment]
And that is a problem how? Using 100% could just mean it's very good at taking advantage of your CPU. Minifying images is very resource intensive.

**Comment by pavelblednov** [comment]
in previous versions of the processor was not loaded at 100% and it was all good

**Comment by dotmagic** [comment]
I would be worried if it's not 100% :)
All I can guess is the imagemin module was updated and it's more efficient using the full CPU power.

**Comment by sindresorhus** [comment]
In the latest version I've limited the concurrency to 8 instead of 16, which should help this.
