### ISSUE TITLE
 Each update npm package on a variety of inexplicable error, ask you to have no self-test to submit ah?

### ISSUE THREAD

**Issue by season19840122** [sindresorhus/gulp-imagemin#235]
Plug-in update after this, the whole project can not run up!
![qq 20161110163926](https://cloud.githubusercontent.com/assets/3078392/20169807/7a4431c6-a764-11e6-9e71-7ad5a25bbe99.jpg)

**Comment by noderat** [comment]
This looks like a duplicate of #232 

@season19840122 are you using yarn?
