### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by tomatojacky** [sindresorhus/gulp-imagemin#237]
(node:49505) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit

then i run the task , in directory "static" ,some pictures are missing 

node v7.0.0
npm v3.10.8
gulp -v
[21:59:42] CLI version 1.2.2
[21:59:42] Local version 3.9.1

"gulp-imagemin": "^3.1.1"

**Comment by tomatojacky** [comment]
gulp.task('default', () =>
    gulp.src('source/images/**/*')
        .pipe(imagemin())
        .pipe(gulp.dest('static/images'))
);

the source img path i use  "**/*"
the picture's directory is: 
"
source/images/1.png  
source/images/user/1.png 
source/images/user/2.png 
"
picture's directory has some pictures and some directories.

I remember in windows ,  run gulp is ok,
in this mac ,see up warning , and  missing some pictures in static directory

**Comment by tomatojacky** [comment]
when i change the node Version to 5.0.0 ,the waring disappear，
but missing some pictures in static directory

**Comment by artemartemov** [comment]
Also having the same issue

**Comment by tomatojacky** [comment]
@artemartemov  i change nodeJs version to 5.0.0, the waring disappear, ///
but  run gulp task,  in directory "static" ,some pictures are missing
so ,change your node version

**Comment by JeisonSanchez** [comment]
I have the same error. The problem occurs only if it is present imagenin.optipng()

If you use this way everything works fine:

.pipe( imagemin([
	imagemin.gifsicle(),
	imagemin.jpegtran(),
	// imagemin.optipng(),
	imagemin.svgo()
]) )

**Comment by quasiDigi** [comment]
@JeisonSanchez, aren't you taking away the png optimisation like this?
With the same issue I've put **.setMaxListeners(0)** at the start of the **imagemin** task and it seems to work well now.  
I am no specialist in the matter so maybe there is a better way.

**Comment by jsilvermist** [comment]
A way to remove the error is only pipe through image files, eg. using gulp-if:

```js
...
.pipe(gulpif(/\.(jpg|jpeg|png|gif|svg)$/, imagemin()))
```

**Comment by opdavies** [comment]
I'm having the same issue, and also it seems to be related to `optipng`.

If I exclude .png files, the error goes away.

Errors:

```
gulp.src('assets/images/**/*.{jpg,jpeg,png,gif,svg}')
        .pipe(plugins.imagemin())
        .pipe(gulp.dest('source/assets/images'));
```

No error:

```
gulp.src('assets/images/**/*.{jpg,jpeg,gif,svg}')
        .pipe(plugins.imagemin())
        .pipe(gulp.dest('source/assets/images'));
```

**Comment by XhmikosR** [comment]
Does this still happen with the latest Node.js + npm packages?
