### ISSUE TITLE
Skip JPG images

### ISSUE THREAD

**Issue by dotmagic** [sindresorhus/gulp-imagemin#243]
I like to optimize only PNG and SVG Files and keep JPG untouched. I know jpegtran is lossless, but i like to save processing power and they're already quite well optimized. I've tried to archive it with changing the plugins option. But imagemin still process all images.

Here's my image task:
```javascript
gulp.task('images', function() {
    return gulp.src(pkg.config.images.src, { since: gulp.lastRun('images') })
        .pipe(gulpif(is_production, imagemin({
            plugins: [
                imagemin.optipng(), imagemin.svgo()
            ]
        })))
        .pipe(gulp.dest(pkg.config.images.dest))
});
```

**Comment by sindresorhus** [comment]
> But imagemin still process all images.

How do you know it does?

Imagemin should only run on the images the chosen plugins support.

Submit a failing test here and I'll take a closer look.
