### ISSUE TITLE
SVG image ends up as just the self-closed root svg element when passed through imagemin.

### ISSUE THREAD

**Issue by BobbyBabes** [sindresorhus/gulp-imagemin#246]
In npm package https://www.npmjs.com/package/uikit there is a `uikit/dist/images/icons.svg` file.
When I pass it through `gulp-imagemin` it ends up as just the self-closed root svg element :  `<svg xmlns="http://www.w3.org/2000/svg" />`. Nothing more.

I work around this by conditioning the call to ``imagemin``. But would still like to compress `icons.svg`.

**My workaround :**

```
gulp.task('images', () => {
  return gulp.src(config.images.toolkit.src)
     // icons.svg ends up as just the self-closed root element : <svg xmlns="http://www.w3.org/2000/svg" />.
    .pipe(gulpif(['*','!icons.svg'], imagemin()))
    .pipe(gulp.dest(config.images.toolkit.dest));
});
```

I realise that there is a possibility that the svg file could be at fault. But my editor doesn't whinge about anything.

**To reproduce
My gulpfile.js with irrelevant parts left out (tested that the issue occurs) :**
Called from project root with : `./node_modules/gulp/bin/gulp.js --dev`.

```
const gulp = require('gulp');
const imagemin = require('gulp-imagemin');
const gutil = require('gulp-util');
const gulpif = require('gulp-if');
const runSequence = require('run-sequence');


// configuration
const config = {
  dev: gutil.env.dev,
  prod: gutil.env.production,
  styles: {
  },
  scripts: {
  },
  toolkit: {
  },
  images: {
    toolkit: {
      src: ['src/assets/toolkit/images/**/*', 'node_modules/uikit/dist/images/**/*'],
      dest: 'dist/assets/toolkit/images',
      watch: ['src/assets/toolkit/images/**/*', 'node_modules/uikit/dist/images/**/*'],
    },
  },
  videos: {
  },
  templates: {
  },
  pages: {
  },
  dest: 'dist',
};


gulp.task('images', () => {
  return gulp.src(config.images.toolkit.src)
    .pipe(imagemin())
    .pipe(gulp.dest(config.images.toolkit.dest));
});


// default build task
gulp.task('default', () => {

  // define build tasks
  const tasks = [
    'images',
  ];

  // run build
  runSequence(tasks, () => {
    if (config.dev) {
      // gulp.start('serve');
    }
  });

});
```

**Comment by anderskleve** [comment]
I'm having the exact same experience. Running gulp-svgmin in a separate task works like a charm on the very same .svg file.

**Comment by BobbyBabes** [comment]
@anderskleve I'm leaving this issue open.
But I'm going to unsubscribe from this issue because I stopped using this, 1 month after opening this issue.
If you're also not interested anymore comment in here and I'll close this issue altogether.
