### ISSUE TITLE
specifying `plugins` array doesn't overwrite defaults

### ISSUE THREAD

**Issue by olets** [sindresorhus/gulp-imagemin#251]
The readme and the [3.0.0 release notes](https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0) state that passing `plugins` will fully replace the defaults. However in testing (v3.1.1) using

```js
.pipe(imagemin([
      imagemin.jpegtran({progressive: true})
]))
```

does still optimize SVGs. The behavior (in this case at least) is as if the passed options are being merged with the defaults

**Comment by mixrich** [comment]
+1. The same probles with version 3.2.0.
I wanna minify just jpeg and png (in screenshot just jpg for test), but svg files are going through imagemin too http://take.ms/U6z47.

**Comment by kevva** [comment]
All images goes through `imagemin`, otherways they would get lost. We could possibly measure the length of the resulting `Buffer` against the original one to tweak our success message a bit. Like `4 images minified (4 ignored)` or something. @sindresorhus wdyt?

**Comment by sindresorhus** [comment]
Sure
