### ISSUE TITLE
No longer compiling in Node 4.4.7

### ISSUE THREAD

**Issue by benjamin-sweeney** [sindresorhus/gulp-imagemin#253]
I've been using this as a dependency for multiple projects and have had no issue running this with node `v4.4.7`, but recently it seems that it (^3.0.1) will no longer compile with this version of node. When I installed, all of the tests passed. The package here states node >=4.

I used nvm to try node `v6.9.0` and everything compiled fine.

**Comment by siraajahmed** [comment]
I had the same issue. Using `v6.10.1` and seems to work fine.

**Comment by thedewpoint** [comment]
Also having this issue

**Comment by kevva** [comment]
Can you please provide some errors or a more detailed explanation of what happens?

**Comment by kevva** [comment]
Going to close for a lack of activity.
