### ISSUE TITLE
Skipping files which give "Premature end of JPEG file"

### ISSUE THREAD

**Issue by rugggger** [sindresorhus/gulp-imagemin#254]
When using gulp-imagemin to minimize thousands of files (16,000).

In this directory there are about a 1000 damaged files that give "Premature end of JPEG file" error.

Is there a way to skip optimization for these files without crashing the task?

Does anyone have a solution ?

LOG: 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Premature end of JPEG file

    at Promise.all.then.arr (D:\php_workspace\photo_shrink\2f076e49f92998893f1b4004ebf9de6e\node_modules\execa\index.js:202:11)


```

> 
> CODE:
> gulp.task('default', function(){
>     return gulp.src([from + '/**/*.png',from + '/**/*.jpg',from + '/**/*.jpeg',from + '/**/*.gif'])
> 		.pipe(filelog())
>         .pipe(imagemin())
>         .pipe(gulp.dest(to));
> });
> 
> gulp.start('default');

**Comment by gerardsmit** [comment]
I had the same issue on Linux, after searching for the issue I've found this issue: https://github.com/danielgtaylor/jpeg-archive/issues/14 and is fixed in Windows (https://github.com/danielgtaylor/jpeg-archive/commit/a6805478ffd130b025e1029c830036801c1c904d) altough it's still presented in Linux.

As workaround I've ran `gulp` on my Windows system.

**Comment by JacobDB** [comment]
Did you figure this out? I'm having the same issue.

**Comment by rugggger** [comment]
I looked in the code 'events.js' where it gives the error and I just commented it out.
That way it doesn't break the process when it fails in the conversion.
(the problem is due to a corrupt JPEG file).
just comment out the 'throw er' line.

**Comment by JacobDB** [comment]
Thanks ☺️ I ended up installing gulp-debug and tracking down which photos it was breaking on and manually removing them.

**Comment by kevva** [comment]
Yes, this is intended. You can check for this in your error handler:

**Comment by ShawnCorrigan** [comment]
I might be missing something, but where is events.js located? I can't seem to find it anywhere

**Comment by Jsonzhang** [comment]
```javascript
 gulp.src('static/*.jpg')
.pipe(imagemin([imagemin.gifsicle(), imagemin.jpegtran(), imagemin.optipng(), imagemin.svgo()], {verbose:true}).on('error', function(e){}))
.pipe(gulp.dest('./dist'))
```

Hope it helps.

**Comment by lusareal** [comment]
> I might be missing something, but where is events.js located? I can't seem to find it anywhere
You can do this in /node-modules/gulp-imagemin/index.js

```
catch (error) {
				//callback(new PluginError(PLUGIN_NAME, error, {fileName: file.path}));
				console.log(error);
				console.log(file.path);				
			}
```
