### ISSUE TITLE
Can't build sucess in ES5

### ISSUE THREAD

**Issue by RayJune** [sindresorhus/gulp-imagemin#258]
just like that

```js
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
gulp.task('imagemin', function(){
	gulp.src('src/images/*')
		.pipe(imagemin())
		.pipe(gulp.dest('dist/images'))
});
```
And terminal throw:

![terminal](http://ww4.sinaimg.cn/large/006HJ39wgy1ffaabqjsraj30oi09kgnt.jpg
)

**Comment by kevva** [comment]
`jpegtran` doesn't exist. Try reinstalling it by running `npm install jpegtran-bin`.
