### ISSUE TITLE
not work in node 6.10.3

### ISSUE THREAD

**Issue by bi-kai** [sindresorhus/gulp-imagemin#265]
comes a error when calling this code:
`.pipe(imagemin())`

I installed:
`npm i --save-dev imagemin-gifsicle imagemin-jpegtran imagemin-optipng imagemin-svgo  gulp-imagemin`

the error:
![image](https://cloud.githubusercontent.com/assets/15070379/26485110/3995c8ec-4228-11e7-90e4-ee4350f1ef17.png)

**Comment by kevva** [comment]
Needs more information, like a detailed error message for example.

**Comment by bi-kai** [comment]
@kevva how can i get the detail error message in gulp pipeline?

**Comment by kevva** [comment]
Listen on the error event and log the error.

**Comment by linyuzhao** [comment]
Hey,man~ Have you solved this problem?  I've gotten same with yours.

**Comment by bi-kai** [comment]
@linyuzhao not yet.

**Comment by zhohon** [comment]
not work in 6.9.5 too， change to 4.X.X work fine。

**Comment by bi-kai** [comment]
@kevva have you test it under node 6.x?

**Comment by kevva** [comment]
Yes, I've tested it in all major versions.

**Comment by bi-kai** [comment]
@kevva That's strange, many persion have this problem. 
Should it be I missed some additional modules or other tools such as ruby, etc?
Could you test this again in a clean path environment?

**Comment by kevva** [comment]
Could you instead do what I suggested above? Otherwise it's impossible to track this down.

> Listen on the `error` event and log the error.

**Comment by bi-kai** [comment]
Ok, I will try it latter.

**Comment by ulivz** [comment]
Maybe it's caused by http://nodejs.cn/doc/node/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe ?

> To make the creation of Buffer objects more reliable and less error prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.

**Comment by arturparkhisenko** [comment]
@bi-kai got the same error today for the 3.4.0 release.
Reverted back to the 3.3.0.
Dunno why, i looked into changes, nothing special, maybe it's a plugin dependency issue.
And i dont understand why all errors are encoded with wrong characterset. Maybe someone can try to decode it in someway?

**Comment by XhmikosR** [comment]
Does this still happen with the latest Node.js + npm packages?

**Comment by arturparkhisenko** [comment]
@XhmikosR new version was released `7 hours ago`, I'll try it today.

**Comment by arturparkhisenko** [comment]
@XhmikosR @bi-kai it works for me ✅. Try to run your own tests.
