### ISSUE TITLE
Imagemin being very slow

### ISSUE THREAD

**Issue by rask** [sindresorhus/gulp-imagemin#267]
I'm using gulp-imagemin on a project to optimize static images (JPG, PNG, and SVG).

Currently my other tasks (Sass, JS, PHP-related, etc.) are run with expected results (most take less than 2 seconds to run through), but my imagemin task takes 30-40 seconds minimum to complete.

My `package.json`:

```json
{
  "private": true,
  "devDependencies": {
    "browser-sync": "^2.18.8",
    "dotenv": "^4.0.0",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-clean-css": "^2.0.11",
    "gulp-imagemin": "^3.0.1",
    "gulp-sass": "^2.3.2",
    "gulp-sort": "^2.0.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-strip-debug": "^1.1.0",
    "gulp-uglify": "^1.5.4",
    "gulp-util": "^3.0.7",
    "gulp-wp-pot": "^1.2.2"
  }
}
```

And my imagemin task:

```js
var gulp = require('gulp');
var imageMin = require('gulp-imagemin');

gulp.task('img', function ()
{
    return gulp.src('src/img/**/*.{jpg,jpeg,png,svg}')
        .pipe(imageMin())
        .pipe(gulp.dest('assets/img'));
});
```

Same issue happens when running a watch task.

This setup has worked fine in the past, but now for a week or so I've been seeing the slowdown happen. The current exact version of image-min is 3.3.0.

I would share examples of the images, but this project is not public and I am not allowed. Regular JPGs, PNGs and SVGs only though.

**Comment by rask** [comment]
Introduced `gulp-changed` which partially fixes the issue when developing, but things like CI runs are still slow as often the images are minified from scratch. This introduces unnecessary 30+ seconds of pipeline time spent.

**Comment by rask** [comment]
A finding: I reduced the size of some larger (2MB+, 2000x1000+ pixels) PNGs and the minification time dropped to around 20 seconds (instead of the original over 40 seconds).

Is the PNG minification always more demanding? The PNGs have transparency, could that introduce performance issues on larger images?

**Comment by kevva** [comment]
How many images are you trying to optmize? It's a heavy operation.

**Comment by rask** [comment]
There are under 20 images, but five or six of them are large-ish PNGs. I understand, but 40 seconds is quite long. Might be the JS overhead that makes it longer, unless I'm mistaken. Thanks anyway, I'll try to see if we could commit the optimized PNGs straight to the repo to make things faster. :)

**Comment by kevva** [comment]
Try lowering the `optimizationLevel` on the `optipng` plugin.

**Comment by rask** [comment]
Will have to try that. Thanks for the pointer! :)

**Comment by rask** [comment]
Setting `optimizationLevel` from `3` to `2` cut the optimization time in half for this project (around 12-15s now for imagemin task). Will need to remember this one. Thanks again!
