### ISSUE TITLE
Gulp shows task finished before it actually finishes

### ISSUE THREAD

**Issue by benrondeau** [sindresorhus/gulp-imagemin#270]
When I use the code from the README:

```javascript
gulp.task('imagemin', function() {
        gulp.src('images/**/*')
            .pipe(imagemin())
            .pipe(gulp.dest('test/'));
    }
);
```

I get a message showing it finishes just milliseconds after staring but the task actually finishes 30 seconds later:

![capture](https://user-images.githubusercontent.com/5001219/28435629-69e76e9a-6d59-11e7-864a-c463904e3cc3.PNG)

Thoughts on why this is occurring?

**Comment by chrisjdiver** [comment]
@benrondeau I have just come across this same problem and came across this issue. 

I noticed I was missing a return, that fixed the issue for me.  

```
gulp.task('imagemin', function() {
        return gulp.src('images/**/*')
            .pipe(imagemin())
            .pipe(gulp.dest('test/'));
    }
);
```

**Comment by kirkbross** [comment]
I have the same problem. Console says all my tasks are done and it serves files, then 15 seconds later imagemin says 'minified 232 images
