### ISSUE TITLE
incompatible with node 8.4.0

### ISSUE THREAD

**Issue by runhwguo** [sindresorhus/gulp-imagemin#274]
WARN node unsupported "node@v8.4.0" is incompatible with gulp-imagemin@3.3.0

**Comment by christiansany** [comment]
Can you be a little bit more specific? This issue doesn't help at all...

**Comment by kevva** [comment]
Not an issue with this module. We're depending on Node.js `>=4` so to me it sounds like an `npm` issue. Try upgrading `npm` or installing again.
