### ISSUE TITLE
Dependencies are not being pulled in on Node version <7.x.x

### ISSUE THREAD

**Issue by JFusco** [sindresorhus/gulp-imagemin#275]
node: v8.1.2
npm: v5.4.1

The required dependencies are not being pulled in correctly because they require `node":">=0.10.0 <7"`

These are the packages that are failing to install:
"imagemin-gifsicle": "^5.0.0",
"imagemin-jpegtran": "^5.0.0",
"imagemin-optipng": "^5.1.0",
"imagemin-svgo": "^5.1.0"

**Comment by kevva** [comment]
Care to share a more detailed description? What does it give you when you're trying to install?

**Comment by JFusco** [comment]
Hey @kevva 
This was actually an issue with the .npmrc I had. I had --engine-strict=true...I remove it and now it's all working as expected. I will close this. Thanks for the quick response.
