### ISSUE TITLE
"Already optimized" JPGs are not being touched

### ISSUE THREAD

**Issue by djmtype** [sindresorhus/gulp-imagemin#277]
I want to make all jpeg images progressive. 

```
.pipe($.imagemin([
imagemin.jpegtran({progressive: true})
], {verbose: true}
))
```

However, on some jpegs, I am getting _(already optimized)_ tagged on many of them. And when I test them on a site like [http://techslides.com/demos/progressive-test.html](http://techslides.com/demos/progressive-test.html) I am finding out they are not progressive. 

BTW, all of my jpegs have a _.jpg_ extension.

Why is this happening? Is there a workaround?

**Comment by yaaax** [comment]
Hi @kevva
This would be the reason --> https://images.guide/#jpeg-compression-modes.
There may be a way to force choosing  progressive vs original even if the image size has not been improved?
