### ISSUE TITLE
gulp-imagemin removes the contents of the tag style

### ISSUE THREAD

**Issue by EmeraldWeb** [sindresorhus/gulp-imagemin#282]
I use a simple command 
`.pipe(imagemin())` ,
without options, and it always worked well.
Today I updated the **gulp-imagemin**  from version **3.2.0** to **3.4.0** and **node.js** from **6** to **8.9.0**. After the project is assembled, all SVG images has broken style tags, the contents of the tag are deleted, but not the tag itself.
`<defs><style/></defs>`
The use of options `removeStyleElement ` works correctly and either deletes the tag, or not, but the contents of the tag are cleared against the will of the development.

Thanks for attention, I hope this problem will be resolved in the soonest possible patch.

**Comment by yadvendar** [comment]
This is due to its dependency on [imagemin-svgo](https://github.com/imagemin/imagemin-svgo)

**Comment by sindresorhus** [comment]
The mistake was reverted: https://github.com/imagemin/imagemin-svgo/commits/master
