### ISSUE TITLE
When installing for the first time, pre-build log messages break TeamCity build.

### ISSUE THREAD

**Issue by olthof** [sindresorhus/gulp-imagemin#283]
Hello, firstly thank you for creating this tool. It's been very helpful.

I have found one issue with this tool (I think). When you install for the test time, there are some pre-build tests that are done. These tests generate a log with the characters "âˆš" out the front. This is meant to show as a tick, but instead shows as these weird characters which break my TeamCity build.

![image](https://user-images.githubusercontent.com/1088778/32428786-c084b740-c31b-11e7-8a6e-f2b9e32e639c.png)

It would be good to fix these characters so that doesn't happen.

**Comment by sindresorhus** [comment]
Those are just normal Unicode characters. Report the issue on the TeamCity issue tracker instead. It should be able to handle Unicode.
