### ISSUE TITLE
Images are skipped when using "pump" for error handling

### ISSUE THREAD

**Issue by brendanfalkowski** [sindresorhus/gulp-imagemin#285]
While rewriting the error handler for my gulpfile to provide details on JS compilation failures, I replaced `gulp-plumber` with `pump` to capture more detail.

* https://www.npmjs.com/package/gulp-plumber
* https://www.npmjs.com/package/pump

Without thinking this would matter (it does), I also rewrote my `image` task from this:

```javascript
gulp.task('image', function () {
    var task = config.tasks.image;

    return gulp
    .src(task.src)
    .pipe(changed(task.dest))
    .pipe(imagemin(task.imageminOptions))
    .pipe(gulp.dest(task.dest))
    .pipe(gulpif(!isProduction, notify(task.notifyOptions)));
});
```

To this, which uses `pump` like other tasks:

```javascript
gulp.task('image', function () {
    var task = config.tasks.image;

    pump([
        gulp.src(task.src),
        changed(task.dest),
        imagemin(task.imageminOptions),
        gulp.dest(task.dest),
        gulpif(!isProduction, notify(task.notifyOptions))
    ], reportError);
});
```

For reference, here's the task config object:

```javascript
imageTask: {
    dest: path.assets + 'img/build',
    imageminOptions: [
        imagemin.gifsicle({
            interlaced: true
        }),
        imagemin.jpegtran({
            progressive: true
        }),
        imagemin.optipng({
            optimizationLevel: 3
        }),
        imagemin.svgo({
            plugins: [
                { removeTitle:   true },
                { removeViewBox: false },
                { removeXMLNS:   false }
            ]
        })
    ],
    notifyOptions: {
        title: 'Image',
        message: 'Done',
        onLast: true
    },
    src: [
        path.assets + 'img/src/**/*'
    ]
}
```

## Problem

A couple weeks later I noticed some SVG icons weren't appearing on the site. They weren't in the `task.dest` folder at all. Every time I re-ran the image task it quit at roughly (but not the same point) while processing the globed folder of various image files.

This had me stumped for a bit.

* Tried updating packages. No change.
* Tried updating Node. No change.
* Tried excluding properties from the `imageminOptions` object. No change.
* Tried changing `task.src` from `path/**/*` to just `path/**/*.svg`. This actually worked, but isn't a solution as I need to process all image file types.

## Workaround

Then I remembered that this was working before I rewrote the task with `pump`. I was not using `gulp-plumber` in the image task before.

I reverted the task back to the "standard" gulp way (piping the stream) and it works.

## Reason

No idea why this doesn't work. Seems like `pump` should handle a stream from `gulp-imagemin` the same as any other. But it can't (for whatever reason) and silently fails without processing the remaining images.

Hopefully this helps someone else debug if they notice images are getting dropped.

## Related Reference

Other issues related to skipped files:
https://github.com/sindresorhus/gulp-imagemin/issues?utf8=%E2%9C%93&q=skip%20

**Comment by sindresorhus** [comment]
You have to return the stream so Gulp knows when it's done:

```js
gulp.task('image', function () {
    var task = config.tasks.image;

    return pump([
        gulp.src(task.src),
        changed(task.dest),
        imagemin(task.imageminOptions),
        gulp.dest(task.dest),
        gulpif(!isProduction, notify(task.notifyOptions))
    ], reportError);
});
```

**Comment by brendanfalkowski** [comment]
@sindresorhus — Thank you for the reply!

Using `return pump()` properly processes all images, but I'm not sure it's the best dev experience.

The Pump example in the Gulp docs uses `pump` (not `return pump`):
https://github.com/gulpjs/gulp/blob/master/docs/why-use-pump/README.md#using-pump

For my JS/CSS/linting tasks it works fine either way, but my `image` task doesn't work without `return pump`.

### Dev experience

I say it's a worse dev experience because when `return pump` is used, the console fills up with some non-helpful Node error output. Pump is supposed to prevent that.

Here's my console when forcing an error in my CSS task using `return pump`:

<img width="651" alt="screen shot 2017-12-07 at 10 53 53 pm" src="https://user-images.githubusercontent.com/214924/33754570-b3038710-dba1-11e7-89bb-e42dab472982.png">

And the same error with `pump` (no return):

<img width="649" alt="screen shot 2017-12-07 at 10 53 03 pm" src="https://user-images.githubusercontent.com/214924/33754578-bbe31a12-dba1-11e7-9a4d-c2e4f85cc9f8.png">

It seems intentional not to `return pump` since the docs suggest this approach, and it's nicer looking.

Not sure if there's anything you can do in the `gulp-imagemin` package.

For me, everything works fine letting my "image" task using the standard `return gulp` and other tasks not returning `pump`.

**Comment by sindresorhus** [comment]
You should always return. The pump example is incorrect.

**Comment by sindresorhus** [comment]
There’s nothing wrong with this plugin.
