### ISSUE TITLE
SVGO plugins don't appear to work with gulp-cache

### ISSUE THREAD

**Issue by bobbwal** [sindresorhus/gulp-imagemin#286]
The SVGO plugin settings are ignored when using the following with gulp-cache.
```
.pipe(cache(imagemin([
    imagemin.svgo({ plugins: [{cleanupIDs: false}]})
])))
```

Any ideas?
Thanks

**Comment by sindresorhus** [comment]
Sounds like a `gulp-cache` problem if it works without it. Report the issue over there instead.
