### ISSUE TITLE
Chrome can't render compressed SVG images.

### ISSUE THREAD

**Issue by hibikikudo** [sindresorhus/gulp-imagemin#288]
Because chrome can't read `xlink:href="data:img/png;base64` attribute.
Meanwhile, `xlink:href="data:image/png;base64` is OK.
This is a known issue with Chrome. https://css-tricks.com/forums/topic/svg-css-background-image-not-showing-in-chrome
Is there anybody who fix this problem?

**Comment by sindresorhus** [comment]
This issue should be opened on https://github.com/svg/svgo instead ;)
