### ISSUE TITLE
Prevent updating images if no changes?

### ISSUE THREAD

**Issue by svivian** [sindresorhus/gulp-imagemin#294]
Whenever I run `gulp-imagemin` it touches every file (i.e. the file "modified" time changes), regardless of whether it is optimized or not. Is it possible to only update the files that changed? Would make it easier for uploading and such.

I looked at `gulp-changed` but that doesn't appear to get changed files in the stream itself, only modified files on disk. For example when I pipe `changed(imageDir)` after `imagemin()` it doesn't touch any files even though it says "saved 3.38 kB - 2.4%" for one.

**Comment by sindresorhus** [comment]
That's outside the scope of this plugin. See: https://github.com/gulpjs/gulp#incremental-builds

**Comment by svivian** [comment]
OK thanks, managed to find a workaround using `gulp-cached`.
