### ISSUE TITLE
Percentage override

### ISSUE THREAD

**Issue by jareha** [sindresorhus/gulp-imagemin#297]
Is it possible to extend this such that we can create a percentage override? My team would like to avoid optimizing images that have already been optimized using a threshold of 3% (or thereabouts).

https://github.com/sindresorhus/gulp-imagemin/blob/cb12e3332dce75dd581a907bb80fa8ce4e61c183/index.js#L63

**Comment by sindresorhus** [comment]
Sorry, not interested in having something like that here.
