### ISSUE TITLE
Gulp Util is deprecated

### ISSUE THREAD

**Issue by ptoly** [sindresorhus/gulp-imagemin#298]

**Comment by growdigital** [comment]
I came across this as well, via gulp warning message:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by Eoler** [comment]
It looks like fix is not overly complicated: https://github.com/zbennett10/gulp-imagemin/commit/b73bf763ce5bc12dd99710e0cd85889715ffad99

**Comment by sindresorhus** [comment]
This was already fixed a long time ago: https://github.com/sindresorhus/gulp-imagemin/commit/adb1e87c00cdf8bf6be9fd6bd5ff0eb7a23c3ac8

**Comment by dak** [comment]
@sindresorhus It looks like the issue is there's a transitive dependency (`bin-wrapper`) that is still relying on an old version of `download` that has the issue.

See: https://github.com/kevva/bin-wrapper/issues/55

```
─┬ gulp-imagemin@4.1.0
│ └─┬ imagemin-gifsicle@5.2.0
│   └─┬ gifsicle@3.0.4
│     └─┬ bin-wrapper@3.0.2
│       └─┬ download@4.4.3
│         └─┬ gulp-decompress@1.2.0
│           └── gulp-util@3.0.8  deduped
```
