### ISSUE TITLE
option to disable a plugin

### ISSUE THREAD

**Issue by x4m3** [sindresorhus/gulp-imagemin#300]
i use another tool for my svg files, is there a way to disable them in `gulp-imagemin`?

in the meantime i just do not add the`svg` extension in my `gulp.src`, like that:
`gulp.src('src/*.{jpg,JPG,jpeg,JPEG,png,gif}')`

thank you

**Comment by sindresorhus** [comment]
Use the `plugins` option or just filter out SVG files before they hit this plugin (`gulp-if` or `gulp-filter`).

**Comment by x4m3** [comment]
thank you
