### ISSUE TITLE
Install hangs on Linux

### ISSUE THREAD

**Issue by Tobsta** [sindresorhus/gulp-imagemin#301]
When I try to install `gulp-imagemin` on my Arch Linux machine using npm 5.7.1 (`npm i -D gulp-imagemin`) it hangs when extracting the module 'fsevents'.

When I try to intall plain `imagemin`, it works, and comes up with a warning saying `SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch
":"x64"})`

Is the module `fsevents` listed as a required dependency for `gulp-imagemin` (but not `imagemin`) despite platform incompatibilities or something?

**Comment by dimitrieh** [comment]
@Tobsta fsevents is a dependency needed on macos only as far as I know. not needed on any other OS, so should be safe to ignore
