### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by yinjiefeng** [sindresorhus/gulp-imagemin#302]
$ npm install --save-dev gulp-imagemin

install failed on windows 10
using npm@5.3.0
using node@v8.4.0

error log(part):

7192 silly doReverseSerial unbuild 4791
7193 silly unbuild gulp-imagemin@3.4.0
7194 info lifecycle gulp-imagemin@3.4.0~preuninstall: gulp-imagemin@3.4.0
7195 info lifecycle gulp-imagemin@3.4.0~uninstall: gulp-imagemin@3.4.0
7196 verbose unbuild rmStuff gulp-imagemin@3.4.0 from E:\Git-Jmyd-Web\fullview\node_modules
7197 info lifecycle gulp-imagemin@3.4.0~postuninstall: gulp-imagemin@3.4.0
7198 silly unbuild chalk@2.1.0
7199 info lifecycle chalk@2.1.0~preuninstall: chalk@2.1.0
7200 info lifecycle chalk@2.1.0~uninstall: chalk@2.1.0
7201 verbose unbuild rmStuff chalk@2.1.0 from E:\Git-Jmyd-Web\fullview\node_modules
7202 verbose unbuild rmStuff in E:\Git-Jmyd-Web\fullview\node_modules\gulp-imagemin\node_modules
7203 info lifecycle chalk@2.1.0~postuninstall: chalk@2.1.0
7204 silly unbuild through2
7205 info lifecycle undefined~preuninstall: undefined
7206 info lifecycle undefined~uninstall: undefined
7207 silly unbuild xtend
7208 info lifecycle undefined~preuninstall: undefined
7209 info lifecycle undefined~uninstall: undefined
7210 silly unbuild readable-stream
7211 info lifecycle undefined~preuninstall: undefined
7212 info lifecycle undefined~uninstall: undefined
7213 silly unbuild util-deprecate
7214 info lifecycle undefined~preuninstall: undefined
7215 info lifecycle undefined~uninstall: undefined
7216 silly unbuild fancy-log
7217 info lifecycle undefined~preuninstall: undefined
7218 info lifecycle undefined~uninstall: undefined
7219 silly unbuild time-stamp
7220 info lifecycle undefined~preuninstall: undefined
7221 info lifecycle undefined~uninstall: undefined
7222 silly unbuild isarray
7223 info lifecycle undefined~preuninstall: undefined
7224 info lifecycle undefined~uninstall: undefined
7225 silly unbuild chalk
7226 info lifecycle undefined~preuninstall: undefined
7227 info lifecycle undefined~uninstall: undefined
7228 verbose unlock done using C:\Users\jeff\AppData\Roaming\npm-cache\_locks\staging-16f3c220c913cc89.lock for E:\Git-Jmyd-Web\fullview\node_modules\.staging
7229 warn chizi@0.0.1 No repository field.
7230 verbose stack TypeError: Cannot read property '0' of undefined
7230 verbose stack     at rmStuff (C:\Program Files\nodejs\node_modules\npm\lib\unbuild.js:61:24)
7230 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
7230 verbose stack     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
7230 verbose stack     at lifecycle.then.then (C:\Program Files\nodejs\node_modules\npm\lib\install\action\unbuild.js:12:12)
7230 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
7230 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
7230 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
7230 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
7230 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
7230 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
7230 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
7230 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
7230 verbose stack     at runCallback (timers.js:781:20)
7230 verbose stack     at tryOnImmediate (timers.js:743:5)
7230 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
7231 verbose cwd E:\Git-Jmyd-Web\fullview
7232 verbose Windows_NT 10.0.16299
7233 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-imagemin"
7234 verbose node v8.4.0
7235 verbose npm  v5.3.0
7236 error Cannot read property '0' of undefined
7237 verbose exit [ 1, true ]

**Comment by sindresorhus** [comment]
That doesn't look relevant to this module. Seems the error is coming from npm.
