### ISSUE TITLE
Progressiv mode dont work

### ISSUE THREAD

**Issue by PersonalityFox** [sindresorhus/gulp-imagemin#305]
Hi
I try use with only option `progressiv: true`.
My pictures decreased in size but progressiv not work.
Compare result in photoshop and i set trottle in Chrome http://prntscr.com/j2uftb.
Tested only jpg and png. 

```
...
.pipe($.imagemin({
	progressive: true,
	verbose: true
}))
...

[14:42:16] gulp-imagemin: ✔ Burn.jpg (saved 12.5 kB - 11.7%)
[14:42:17] gulp-imagemin: ✔ Burn.png (saved 258 kB - 29.6%)
```

**Comment by sindresorhus** [comment]
I think you missed the upgrade note: https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0
