### ISSUE TITLE
npm audit:  Memory Exposure.

### ISSUE THREAD

**Issue by samcarecho** [sindresorhus/gulp-imagemin#308]
NPM audit is complaining about several moderate level vulnerabilities in a dependency required by gulp-imagemin.

│ moderate      │ Memory Exposure
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-gifsicle > gifsicle > bin-build > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

│ moderate      │ Memory Exposure
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-gifsicle > gifsicle > bin-wrapper > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

│ moderate      │ Memory Exposure 
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-jpegtran > jpegtran-bin > bin-build > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

│ moderate      │ Memory Exposure
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-jpegtran > jpegtran-bin > bin-wrapper > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

│ moderate      │ Memory Exposure
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-optipng > optipng-bin > bin-build > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

│ moderate      │ Memory Exposure
│ Package       │ tunnel-agent
│ Dependency of │ gulp-imagemin
│ Path          │ gulp-imagemin > imagemin-optipng > optipng-bin > bin-wrapper > download > caw > tunnel-agent
│ More info     │ https://nodesecurity.io/advisories/598

**Comment by ionceban** [comment]
Hi, any news here?

**Comment by Jamesking56** [comment]
Last commit was February, I think this repo is dead.

**Comment by Jikstra** [comment]
@sindresorhus is still active on github, maybe he can update the dependency or at least merge a pr which fixes this?

**Comment by gustawdaniel** [comment]
@sindresorhus can you update dependencies?

**Comment by anselmbradford** [comment]
These dependencies have [been updated](https://github.com/imagemin/imagemin-gifsicle/issues/22), so hopefully soon here too!
