### ISSUE TITLE
Disable SVG optimisation

### ISSUE THREAD

**Issue by MattPurland** [sindresorhus/gulp-imagemin#310]
Hi,

I'm finding that SVG optimisation is causing more problems than it solves, I'd prefer to manually optimise SVGs. Is it possible to disable it via the configuration? Currently I'm removing the imagemin-svg module, but annoyingly it gets reinstalled whenever NPM modules are installed/updated so I have to keep removing it.

Thanks

**Comment by sindresorhus** [comment]
Per docs, you can manually set the `plugins` option and not include the SVGO plugin.
