### ISSUE TITLE
gulp-util deprecation

### ISSUE THREAD

**Issue by spydertad** [sindresorhus/gulp-imagemin#312]
Probably not news but didn't see it in issues when I searched.  Looks like gulp-util@3.0.8 is a dependency.  https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

That said, thanks for the plugin.  Very helpful

**Comment by pachabhaiya** [comment]
Looks like this PR didn't completely remove the deprecated `gulp-util`

$ npm install
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5`

$ npm ls gulp-util

```
└─┬ gulp-imagemin@4.1.0
  └─┬ imagemin-gifsicle@5.2.0
    └─┬ gifsicle@3.0.4
      └─┬ bin-build@2.2.0
        └─┬ download@4.4.3
          └─┬ gulp-decompress@1.2.0
            └── gulp-util@3.0.8
```

---

package-json.lock
```
"gulp-decompress": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/gulp-decompress/-/gulp-decompress-1.2.0.tgz",
      "integrity": "sha1-jutlpeAV+O2FMsr+KEVJYGJvDcc=",
      "dev": true,
      "requires": {
        "archive-type": "^3.0.0",
        "decompress": "^3.0.0",
        "gulp-util": "^3.0.1",
        "readable-stream": "^2.0.2"
      }
    },
```

**Comment by d0whc3r** [comment]
There is a pull request in gifsicle that solves this issue
https://github.com/imagemin/gifsicle-bin/pull/96
Now, only need to be approved

**Comment by d0whc3r** [comment]
Similar pull request was opened in jpegtran: https://github.com/imagemin/jpegtran-bin/pull/90
and optipng: https://github.com/imagemin/optipng-bin/pull/101

**Comment by garrettw** [comment]
This was just solved in jpegtran and will need a version bump to the dependency here.
See https://github.com/imagemin/jpegtran-bin/issues/84
