### ISSUE TITLE
Can the source and dest location be the same? Can this be used to overwrite images?

### ISSUE THREAD

**Issue by jcklpe** [sindresorhus/gulp-imagemin#319]
As in, if I have an image here" ./uploads/image.jpg" when it is piped through gulp, can I have it save to "./uploads/image.jpg", overwriting the previous file?

**Comment by henrahmagix** [comment]
I have done like so:
```js
gulp.task('imagemin', function() {
    gulp.src('public/images/*')
        .pipe(imagemin())
        .pipe(gulp.dest('public/images'));
});
```
and it worked fine for me =)

**Comment by sindresorhus** [comment]
This is a general Gulp question and not related to this plugin.
