### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by sungwoncho** [sindresorhus/gulp-imagemin#321]
While trying to upgrade gulp-imagemin from 4.x.x to the latest 5.x.x, I could not find any CHANGELOG or notes in the GitHub release. Would you be able to specify what breaking changes were introduced in the new major release in a form of a change log or release note?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-imagemin/releases/tag/v5.0.0
