### ISSUE TITLE
Ignoring .db files sends imagemin into endless loop

### ISSUE THREAD

**Issue by wgstjf** [sindresorhus/gulp-imagemin#322]
Hi guys,

We're using imagemin (^3.1.1) as part of a Wordpress starter theme and within a Windows environment.  We need to ignore the Thumbs.db file in the source image folder so have modified the code as follows:

FROM THIS
------------
```php
// Optimize images, move into assets directory
   gulp.task('images', function() {
   return gulp.src(SOURCE.images)
   .pipe(plugin.imagemin())
  .pipe(gulp.dest(ASSETS.images))
});
```

TO THIS
---------
```php
// Optimize images, move into assets directory
   gulp.task('images', function() {
   return gulp.src(SOURCE.images + '.!(db)')
   .pipe(plugin.imagemin())
  .pipe(gulp.dest(ASSETS.images))
});
```

The issue is that having done this, though the Thumbs.db error goes away, it now sends imagemin into a infinite loop after successfully minifying the relevant image as shown below:

![image](https://user-images.githubusercontent.com/3740694/51386557-c46ba780-1b1a-11e9-8698-849108e04eed.png)

Any help on how to prevent this would be greatly appreciated.

Cheers in advance,

Will

**Comment by sindresorhus** [comment]
I don't think this is related to gulp-imagemin. It just accepts a stream of file paths. The problem you're having is with Gulp itself.
