### ISSUE TITLE
Imagemin doesn't overwrite symlinks, instead overwrites original files

### ISSUE THREAD

**Issue by FabianSchmick** [sindresorhus/gulp-imagemin#323]
If I execute the `default` task I would expect:

1. the files in `./web/assets/dist/img/*` get removed
2. symlinks are generated for all files in `./assets/img/**/*.*`
3. all images in `./assets/img/*` should be minified and be put in `./web/assets/dist/img/*`

But the third step does not work correctly. Instead `gulp-imagemin` follows the created symlinks in the `./web/assets/dist/img/` destination directory (step 2) and minifies the original files in `./assets/img/`. It does not overwrite the symlinks with the minified files as I would expect.

```js
var gulp  = require('gulp'),
    imagemin = require('gulp-imagemin'),
    del = require('del');

gulp.task('clean', function () {
    return del(['./web/assets/dist/img/*']);
});

gulp.task('images', function () {
    return gulp.src('./assets/img/**/*.*')
        .pipe(gulp.symlink('./web/assets/dist/img/'));
});

gulp.task('compress', function() {
    return gulp.src('./assets/img/**/*.{jpg,jpeg,png}')
        .pipe(imagemin([
            imagemin.jpegtran({progressive: true}),
            imagemin.optipng({optimizationLevel: 5}),
        ]))
        .pipe(gulp.dest('./web/assets/dist/img/'))
});

gulp.task('default',
    gulp.series(
        'clean',
        'images',
        'compress'
    )
);
```

I hope someone can provide me a solution with `gulp-imagemin` where:

1. Image files from `./assets/img/**/*` were minified
2. All other files from `./assets/img/**/*` were symlinked

in the `./web/assets/dist/img/` destination folder.

**Comment by sindresorhus** [comment]
`gulp-imagemin` doesn't deal with the file system at all. It just gets buffers of data, modifies them, and then sends them back to Gulp. Your issue is a plain Gulp issue and would be better asked on the Gulp support channels.
