### ISSUE TITLE
Error: TypeError: pPipe(...) is not a function

### ISSUE THREAD

**Issue by EthanNYT** [sindresorhus/gulp-imagemin#326]
Still seeing this bug.

Similar issues:
1. https://github.com/sindresorhus/gulp-imagemin/issues/261
2. https://github.com/imagemin/imagemin/issues/243
3. https://github.com/imagemin/imagemin/issues/244

Configuration: 
- `imagemin` v6.1.0
- `gulp-imagemin` v5.0.3
- `gulp-cli` v2.0.1
- `gulp` v4.0.2

Message:
> TypeError: pPipe(...) is not a function
>     at Function.module.exports.buffer ([...]/node_modules/gulp-imagemin/node_modules/imagemin/index.js:71:31)
>     at DestroyableTransform.through.obj ([...]/node_modules/gulp-imagemin/index.js:75:12)
>     at DestroyableTransform._transform ([...]/node_modules/through2-concurrent/through2-concurrent.js:34:15)
>     at DestroyableTransform.Transform._read ([...]/node_modules/readable-stream/lib/_stream_transform.js:184:10)
>     at DestroyableTransform.Transform._write ([...]/node_modules/readable-stream/lib/_stream_transform.js:172:83)
>     at doWrite ([...]/node_modules/readable-stream/lib/_stream_writable.js:428:64)
>     at writeOrBuffer ([...]/node_modules/readable-stream/lib/_stream_writable.js:417:5)
>     at DestroyableTransform.Writable.write ([...]/node_modules/readable-stream/lib/_stream_writable.js:334:11)
>     at Stream.ondata (internal/streams/legacy.js:15:31)
>     at Stream.emit (events.js:182:13)

gulpfile.babel.js:

```js
import gulp from 'gulp';
import imagemin from 'gulp-imagemin';
import imageminWebp from 'imagemin-webp';
import newer from 'gulp-newer';

function images(cb) {
	return gulp
		.src('src/img/**/*')
		.pipe(newer('dist/img'))
		.pipe(imagemin([
			imagemin.gifsicle({ interlaced: true }),
			imagemin.jpegtran({ progressive: true }),
			imagemin.optipng({ optimizationLevel: 5 }),
			imagemin.svgo({
				plugins: [
					{
						removeViewBox: false,
						collapseGroups: true,
					},
				],
			}),
		]))
		.pipe(gulp.dest('dist/img'))
		.pipe(print())
		.pipe(imagemin('src/img/**/*', 'dist/img', {
			use: [imageminWebp({ quality: 75 })],
		}))
		.pipe(print())
		.on('end', function() {
			log('✔ Images minified');
			cb();
		});
}
```

**Comment by EthanNYT** [comment]
The issue seems to stem from running `.pipe(gulp.dest('...'))` *after* running `gulp-imagemin` (with the `use` option set to a plugin)

**Comment by sindresorhus** [comment]
I cannot reproduce this with the latest version; https://github.com/sindresorhus/gulp-imagemin/releases/tag/v6.0.0
