### ISSUE TITLE
Jpeg compression failure

### ISSUE THREAD

**Issue by worftan** [sindresorhus/gulp-imagemin#329]
I didn't found the wrong reason

10:18:54] Starting 'default'...
[10:18:54] gulp-notify: [Gulp notification] Images compressed
[10:18:54] gulp-notify: [Gulp notification] Images compressed
[10:18:54] gulp-notify: [Gulp notification] Images compressed
[10:18:55] gulp-notify: [Gulp notification] Images compressed
[10:18:55] 'default' errored after 589 ms
[10:18:55] Error in plugin "gulp-imagemin"
Message:
    Command failed: /media/psf/wwwroot/edelbrock/app/design/frontend/GC/Edelbrock/web-src/node_modules/jpegtran-bin/vendor/jpegtran -copy none -progressive -optimize -outfile /tmp/0f7ebc7a-6bf7-45bb-a7db-835267ad35ce /tmp/9ddfd794-680a-49c0-8e11-81948e119a3e

Details:
    code: null
    killed: false
    stdout: 
    stderr: 
    failed: true
    signal: SIGSEGV
    cmd: /media/psf/wwwroot/edelbrock/app/design/frontend/GC/Edelbrock/web-src/node_modules/jpegtran-bin/vendor/jpegtran -copy none -progressive -optimize -outfile /tmp/0f7ebc7a-6bf7-45bb-a7db-835267ad35ce /tmp/9ddfd794-680a-49c0-8e11-81948e119a3e
    timedOut: false
    fileName: /media/psf/wwwroot/edelbrock/app/design/frontend/GC/Edelbrock/web-src/img/arrow_down.jpg
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

**Comment by kevva** [comment]
`SIGSEGV` is a segmentation fault error. What Node.js version are you running?

**Comment by worftan** [comment]
Hi guys.

> 在 2019年9月30日，下午5:21，Kevin Mårtensson <notifications@github.com> 写道：
> 
> SIGSEGV is a segmentation fault error. What Node.js version are you running?
