### ISSUE TITLE
Can't use `mozjpeg` instead of `jpegtran`

### ISSUE THREAD

**Issue by TheDutchCoder** [sindresorhus/gulp-imagemin#330]
The docs say I should be able to call any imagemin plugin from the constructor like so:

```
.pipe(imagemin([
  imagemin.mozjpeg()
]))
```

However that results in: `TypeError: imagemin.mozjpeg is not a function`.

`imagemin-mozjpeg` is installed.

**Comment by kevva** [comment]
Only [these](https://github.com/sindresorhus/gulp-imagemin/blob/master/index.js#L117-L120) are exported directly from this plugin. You have to do this:

```js
const imageminMozjpeg = require('imagemin-mozjpeg');
…
.pipe(imagemin([
    imageminMozjpeg()
]))
```

**Comment by TheDutchCoder** [comment]
Ah thanks! That wasn't clear to me :)

**Comment by kevva** [comment]
We'll gladly accept a PR that improves upon the docs to make it clearer :).

**Comment by tjbulick** [comment]
Wasn't clear for me too. Idk how, but i guess you should rewrite that part of docs
