### ISSUE TITLE
Use `mozjpeg` instead of `jpegtran` by default

### ISSUE THREAD

**Issue by tjbulick** [sindresorhus/gulp-imagemin#333]
Hey!
Seems like mozjpeg is much better than jpegtran and also Google uses this algorithm in its [Squoosh App](https://squoosh.app) by default.
I also tried to compress images and it shows excellent results.
Furthermore, Addy Osmani from still the same Google [advised](https://images.guide) to "run your JPEGs through MozJPEG".
How about switch to MozJPEG for JPEG images?

**Comment by sindresorhus** [comment]
Sure. PR welcome. You need to update the readme and tests too.

**Comment by tjbulick** [comment]
Working on it, PR soon.
