### ISSUE TITLE
Error when npm installing gulp-imagemin 'autoreconf' and '.' command not recognized

### ISSUE THREAD

**Issue by GeroCoded** [sindresorhus/gulp-imagemin#337]
I'm getting the following error after doing `npm install --save-dev gulp-imagemin`

>C:\Users\luis_\Desktop\traversy\gulpexapp>npm install --save-dev gulp-imagemin
>
>gifsicle@4.0.1 postinstall C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\gifsicle
 node lib/install.js
>
>  ‼ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 27015 27015:80
>  ‼ gifsicle pre-build test failed
>  i compiling from source
>  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
"autoreconf" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
>
>
>at Promise.all.then.arr (C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
>
>optipng-bin@6.0.0 postinstall C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\optipng-bin
node lib/install.js
>
>  ‼ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 27015 27015:80
>  ‼ optipng pre-build test failed
>  i compiling from source
>  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\optipng-bin\vendor" --bindir="C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\optipng-bin\vendor""
"." no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
>
>
>at Promise.all.then.arr (C:\Users\luis_\Desktop\traversy\gulpexapp\node_modules\execa\index.js:231:11)
at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN gulpexapp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@4.0.1 (node_modules\gifsicle):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@4.0.1 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@6.0.0 (node_modules\optipng-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@6.0.0 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
>
>gulp-imagemin@6.2.0
updated 1 package and audited 8995 packages in 55.704s
found 0 vulnerabilities

Haven't found any solution out there.

**Comment by GeroCoded** [comment]
Alright, so this is a silly one but finally found it. I just had a key value in my npm config which I guess the installation uses.
> https-proxy = "127.0.0.1:27015"

So I just deleted it:
> npm config delete https-proxy

And finally run with no problems.

**Comment by itrusler** [comment]
I am having the same issue with v7.1.0 on Ubuntu
@GeroCoded solution does not fix
javascript```
> gifsicle@5.0.0 postinstall /home/user/Projects/.srcs/github.com/folder-name/gulp-ingredients-test/test-op-img/node_modules/gifsicle
> node lib/install.js

  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at Promise.all.then.arr (/home/user/Projects/.srcs/github.com/folder-name/gulp-ingredients-test/test-op-img/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

> mozjpeg@6.0.1 postinstall /home/user/Projects/.srcs/github.com/folder-name/gulp-ingredients-test/test-op-img/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@6.0.0 postinstall /home/user/Projects/.srcs/github.com/folder-name/gulp-ingredients-test/test-op-img/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
npm WARN test-op-img@0.0.1 No description
npm WARN test-op-img@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@5.0.0 (node_modules/gifsicle):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@5.0.0 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ gulp-imagemin@7.1.0
added 274 packages from 197 contributors and audited 10521 packages in 28.12s
found 0 vulnerabilities
```
This is the only problem I have seen like mine

**Comment by hpierre74** [comment]
Same error when updating gulp-imagemin to v7.1.0, any idea where it comes from ?

**Comment by joeyliechty** [comment]
did you try disconnecting from VPN, worked for me ;P

**Comment by joeczucha** [comment]
> Same error when updating gulp-imagemin to v7.1.0, any idea where it comes from ?

A bit late to the party but I ran into this when using gulp-imagemin 7.1.0 on Ubuntu. 

The solution was to run `sudo apt-get install libtool automake autoconf nasm` first
