### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by RmRomaning** [sindresorhus/gulp-imagemin#341]
‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Silic0nS0ldier** [comment]
Just hit this issue on Ubuntu 20.04 (WSL2) and CentOS 7 (managed server). Guessing this issue would need to be resolved at `gifsicle`, where I can see a few mentions of `autoreconf` problems.

* https://github.com/imagemin/gifsicle-bin/issues/113
* https://github.com/imagemin/gifsicle-bin/issues/79

I've had to downgrade to 6.2.0 in the meantime.

**Comment by rodrigograca31** [comment]
this needs to be fixed... its breaking tuns of projects all over the web!

**Comment by sindresorhus** [comment]
Closing in favor of the mentioned issues above.
