### ISSUE TITLE
"Couldn't load default plugin gifsicle" with version 7.10

### ISSUE THREAD

**Issue by stefanobartoletti** [sindresorhus/gulp-imagemin#352]
Pretty much as the title says, I'm getting this error when using this plugin.
```
[17:01:58] gulp-imagemin: Couldn't load default plugin "gifsicle"
```
I'm getting no other info from the output messages. Let me know if you need more feedback.

**Comment by bjmiller121** [comment]
I'm seeing this same error. Doesn't seem to prevent the task from running, however I'm only processing jpegs. Version `7.1.0`.

**Comment by stefanobartoletti** [comment]
The task is running, but `gif` images don't seem to be optimized at all.

**Comment by sindresorhus** [comment]
Look at the `npm install` log. This error happens when the plugin failed to install.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
