### ISSUE TITLE
imagemin-svgo upgrade to 9.0

### ISSUE THREAD

**Issue by mbardelmeijer** [sindresorhus/gulp-imagemin#354]
Currently imagemin-svgo is limited to 7.x releases. 9.0 upgrades svgo to 2.0

https://github.com/imagemin/imagemin-svgo/commit/43888a0389bdd4c8e7790d5c2cea25d497a561ea

**Comment by strarsis** [comment]
+1, `prefixIds` `svgo` plugin doesn't work correctly in older releases.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/gulp-imagemin/releases/tag/v8.0.0
