### ISSUE TITLE
Could not load default plugin xxx

### ISSUE THREAD

**Issue by zh-D** [sindresorhus/gulp-imagemin#358]
gulpfile.esm.js:
```javascript
import gulp from "gulp"
import imagemin from 'gulp-imagemin';

export function imageMin(cb) {
    gulp.src('src/images/*')
        .pipe(imagemin())
        .pipe(gulp.dest('dist/images'))
    cb()
}

```

Something goes wrong when I run "gulp imageMin"

![Snipaste_2021-08-30_16-06-38](https://user-images.githubusercontent.com/61453507/131307071-a58bfd0e-78c1-4e3d-81a0-cfebe43926c6.png)

[2021-08-30]
`win10`
`node version: v14.17.4` 
`gulp version: ^4.0.2`
`gulp-imagemin version: ^8.0.0`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
