### ISSUE TITLE
Conflict with Gulp Load Plugins

### ISSUE THREAD

**Issue by DaveyJake** [sindresorhus/gulp-imagemin#361]
The following error message occurs when attempting to load the plugin using `gulp-load-plugins`:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/to/node_modules/gulp-imagemin/index.js
> require() of ES modules is not supported.
> require() of /path/to/node_modules/gulp-imagemin/index.js from /path/to/node_modules/gulp-load-plugins/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
> Instead rename /path/to/node_modules/gulp-imagemin/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /path/to/node_modules/gulp-imagemin/package.json.

I tried making the basic adjustments as suggested but none worked.  Any ideas would be much appreciated.

Cheers 🍻

**Comment by bobbyg603** [comment]
Try the following:
1. `npm i esm`
2. rename gulpfile.js to gulpfile.esm.js
3. Update all your requires to imports
4. `gulp`

**Comment by strarsis** [comment]
@bobbyg603: Thanks for these instructions. Though when I try to run gulp it seems that a file named `gulpfile.js` is expected:
`Error: File not found with singular glob: [...]/gulpfile.js`

**Comment by bobbyg603** [comment]
@strarsis i ended up using gulp/typescript to solve this problem and forgot to update my answer, sorry about that!

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
