### ISSUE TITLE
Is it expected to not work on Node.js 15?

### ISSUE THREAD

**Issue by rizqirizqi** [sindresorhus/gulp-imagemin#363]
I know Node.js 15 is not an LTS release, but is it better to keep it compatible with that version?

![image](https://user-images.githubusercontent.com/6806365/132976756-b8e396e4-1506-4213-bfc5-604c35cf7330.png)

https://github.com/rizqirizqi/webpconvert/runs/3568180914?check_suite_focus=true

**Comment by sindresorhus** [comment]
Node.js 15 is not supported by the Node.js team, hence not supported by third-party packages either.
