### ISSUE TITLE
Breaking in Ubuntu?

### ISSUE THREAD

**Issue by cesarandreu** [sindresorhus/gulp-imagemin#37]
Latest version of gulp-imagemin won't work in Ubuntu.
Ubuntu already includes a version of optipng, and it tries to use that one, since it's an old version it fails with `Error: Lossy operations are not currently supported`.

Not sure how to solve. I'm using gulp-image and it works for png's. They appear to require optipng-bin directly.

Maybe this is an issue related to imagemin itself? If imagemin requires the version of imagemin-optipng that forces it to use v0.7.4 of optipng then it should work. It appears the latest version removed that. [Relevant commit](https://github.com/yeoman/node-optipng-bin/commit/fd427bbbfc258a098ca5c6f3c398fa84ef780d09)

Can't update Ubuntu because it's on CircleCI.

I found these related issues:
https://github.com/gruntjs/grunt-contrib-imagemin/issues/180
https://github.com/gruntjs/grunt-contrib-imagemin/issues/210

**Comment by satblip** [comment]
Thanks @tanertopal !

**Comment by KingScooty** [comment]
:+1:
