### ISSUE TITLE
after updating gulp to version 5, jpg and png files compressed by the gulp-imagemin plugin are not readable

### ISSUE THREAD

**Issue by llcawc** [sindresorhus/gulp-imagemin#382]
after updating gulp to version 5, jpg and png files compressed by the gulp-imagemin plugin are not readable

**Comment by llcawc** [comment]
o, well, that's why I need this {encoding:false} setting when everything was working earlier!

**Comment by llcawc** [comment]
Here is the solution to the problem : we need to add the {encoding:false} in the src() function option. This is not yet available in the gulp documentation.
And this is not a gulp-imagemin problem.
for example, like this:
```
// images task
function images() {
  return src(baseDir + '/assets/images/**/*.*', { base: baseDir, encoding: false })
    .pipe(changed(distDir))
    .pipe(
      imagemin(
        [
          gifsicle({ interlaced: true }),
          mozjpeg({ quality: 75, progressive: true }),
          optipng({ optimizationLevel: 5 }),
          svgo({ plugins: [{ name: 'preset-default', params: { overrides: { removeViewBox: false } } }] }),
        ],
        { verbose: true }
      )
    )
    .pipe(dest(distDir))
}
```

**Comment by madjacky** [comment]
> I'll leave it here. Here is the solution to the problem : we need to add the {encoding:false} in the src() function option. This is not yet available in the gulp documentation. And as it turned out this is not a gulp-imagemin problem. for example, like this:
> 
> ```
> // images task
> function images() {
>   return src(baseDir + '/assets/images/**/*.*', { base: baseDir, encoding: false })
>     .pipe(changed(distDir))
>     .pipe(
>       imagemin(
>         [
>           gifsicle({ interlaced: true }),
>           mozjpeg({ quality: 75, progressive: true }),
>           optipng({ optimizationLevel: 5 }),
>           svgo({ plugins: [{ name: 'preset-default', params: { overrides: { removeViewBox: false } } }] }),
>         ],
>         { verbose: true }
>       )
>     )
>     .pipe(dest(distDir))
> }
> ```

Oh thanks man, I’ve been struggling with this question for 18 hours.
here is my gulpfile code
`
const srcFolder = './src';
const buildFolder = './app';

const srcPaths = {
  srcImagesFolder: `${srcFolder}/img`,
};
const appPaths = {
  buildImagesFolder: `${buildFolder}/img`,
};

const images = () => {
  return src([`${srcPaths.srcImagesFolder}/**/**.{jpg,jpeg,png,svg}`], { encoding: false })
    .pipe(dest(buildtPaths.buildImagesFolder))
}
`

**Comment by juanlopezdev** [comment]
Curiously, it worked for me only in the CommonJS version of Gulp, adding what the friend mentioned about
`{ encoding: false }`, but in the ESM version it does not work, nor does it add the images to the folder where they should go, nor does it throw an error.

Some details:

Code:

```js
export function images() {
    return src(paths.html.src, { encoding: false })
        .pipe(imagemin())
        .pipe(dest(paths.html.dest));
}
```

Gulp version

- CLI version: 3.0.0
- Local version: 5.0.0

Node 

v20.11.1

**Comment by madjacky** [comment]
for me after updating gulp to version 5 when i start gulp console shows gulp-imagemin: Minified 1 image (saved 119 kB - 48.2%) but when i check sizes in src & dist are same 
``` javascript
const images = () => {
  return src([`${paths.imagesFolder.src}/**/**.{jpg,jpeg,png,svg}`], { encoding: false })
    .pipe(gulpif(isProd, imagemin([
      mozjpeg({
        quality: 60,
        progressive: true
      }),
      optipng({
        optimizationLevel: 2
      }),
    ])))
    .pipe(dest(paths.imagesFolder.dist))
}
```
```
gulp-imagemin: Minified 1 image (saved 119 kB - 48.2%)
```

**Comment by keevvinc** [comment]
> I'll leave it here. Here is the solution to the problem : we need to add the {encoding:false} in the src() function option. This is not yet available in the gulp documentation. And as it turned out this is not a gulp-imagemin problem. for example, like this:
> 
> ```
> // images task
> function images() {
>   return src(baseDir + '/assets/images/**/*.*', { base: baseDir, encoding: false })
>     .pipe(changed(distDir))
>     .pipe(
>       imagemin(
>         [
>           gifsicle({ interlaced: true }),
>           mozjpeg({ quality: 75, progressive: true }),
>           optipng({ optimizationLevel: 5 }),
>           svgo({ plugins: [{ name: 'preset-default', params: { overrides: { removeViewBox: false } } }] }),
>         ],
>         { verbose: true }
>       )
>     )
>     .pipe(dest(distDir))
> }
> ```

if it is not in the docs, may i know how did you found this out? it amazes me, lol

**Comment by llcawc** [comment]
> ```js
> ` .... /**/**.{jpg,jpeg,png,svg}`
> ```

The wrong globe
should be like this: ` .... /**/*.{jpg,jpeg,png,svg}`

**Comment by llcawc** [comment]
> > ```
> 
> if it is not in the docs, may i know how did you found this out? it amazes me, lol

Yes, this problem is not yet in the documentation on the site [gulpjs.com ](https://golpas.com/docs/en/api/src#options ), but after I posted the problem [gulp documentation on github](https://github.com/gulpjs/gulp/blob/master/docs/api/src.md#options ).
And I found out about it by studying [closed issues on gulp github](https://github.com/gulpjs/gulp/issues ?q=is %3 released+is %3 closed)

**Comment by madjacky** [comment]
> > ```js
> > ` .... /**/**.{jpg,jpeg,png,svg}`
> > ```
> 
> The wrong globe should be like this: ` .... /**/*.{jpg,jpeg,png,svg}`

Correct me if I’m wrong, but if the glob pattern was incorrect, would it have worked? I mean, after running the gulp command, images appear in the dist/assets/images folder, but for some reason, the imagemin plugin doesn’t optimize them, although, for example, the gulp-webp plugin with the same glob pattern works perfectly

**Comment by llcawc** [comment]
> Correct me if I’m wrong, but if the glob pattern was incorrect, would it have worked? I mean, after running the gulp command, images appear in the dist/assets/images folder, but for some reason, the imagemin plugin doesn’t optimize them, although, for example, the gulp-webp plugin with the same glob pattern works perfectly

I can't tell you the answer, because I have to check it in my work. But I recommend enabling hints with the {verbose:true} directive

```
const images = () => {
  return src([`${paths.imagesFolder.src}/**/*.{jpg,jpeg,png,svg}`], { encoding: false })
    .pipe(
        gulpif( isProd, 
          imagemin(
            [ 
            mozjpeg({ quality: 60, progressive: true }),
            optipng({ optimizationLevel: 2 }),
            ], { verbose: true } )))
    .pipe(dest(paths.imagesFolder.dist))
}
```

**Comment by llcawc** [comment]
The problem is solved
