### ISSUE TITLE
File path length - unable to delete folder on Windows

### ISSUE THREAD

**Issue by u01jmg3** [sindresorhus/gulp-imagemin#56]
When working with `gulp-imagemin` on a Windows machine, the setup of gulp results in a file path that is too long for Windows to be able to delete. This makes it difficult to delete any parent folder containing `gulp-imagemin`.

Similar problem seen here and now fixed: https://github.com/gulpjs/gulp/issues/630

Can anything be done to fix this?

![example](https://cloud.githubusercontent.com/assets/1266205/3941880/5ae416a8-2547-11e4-97c8-76bf8c65ea50.gif)

**Comment by domingos-martins-dw** [comment]
Thanks @ComFreek

**Comment by Sabbir786** [comment]
I suggest to try “Long Path Tool” program

**Comment by KamilaDanielo** [comment]
Try Long path tool. It is really awesome one.

**Comment by dobromir-hristov** [comment]
7Zip did the trick :)

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by marceln** [comment]
You can also try SuperDelete (disclaimer: I'm the author): https://github.com/marceln/SuperDelete

**Comment by fuadhasni** [comment]
SuperDelete worked like a charm
