### ISSUE TITLE
gulp-imagemin is missing some nested folders.

### ISSUE THREAD

**Issue by chenxsan** [sindresorhus/gulp-imagemin#58]
I got this old project, with lots of images scattered under some sub folders, like:
- js
  - styles
    - images
      - a.jpg
  - b.jpg
- images
  - c.png
  - index
    - d.jpg

So, I try this:

```
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
var pngcrush = require('imagemin-pngcrush');

gulp.task('default', function () {
    return gulp.src('src/**/*.{jpg,png,gif}')
        .pipe(imagemin({
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngcrush()]
        }))
        .pipe(gulp.dest('dist'));
});
```

After the task was done, I checked the files count and found that some folders(not empty) with images were left out.

**Comment by tuler** [comment]
I have the same problem. What might be happening?

**Comment by tuler** [comment]
I think I found out what the problem is. Its related to $.cache, which is not keeping track of the whole path.

This is my task:

gulp.task('images', function () {
  return gulp.src('src/assets/images/**/*')
    .pipe($.cache($.imagemin({
      optimizationLevel: 3,
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest('dist/assets/images'))
    .pipe($.size());
});

The problem is that I have an image at 'src/assets/images/a.png' and 'src/assets/images/subdir/a.png'.
The later is not saved.
If I remove the $.cache from the task it works fine.

Found two related references:
https://github.com/google/web-starter-kit/issues/579
https://github.com/jgable/gulp-cache/issues/16

**Comment by pavangupta** [comment]
@tuler I ran into a similar kind of conclusion, but it relates to the way that the gulp.src stream of vinyl files is generated.  The glob is essentially selecting everything inside your src/assets/images/ folder including subdirectories by themselves.  Not too long ago, gulp-cache was was setup to gracefully (and I believe incorrectly) ignore directories.  That's changed and while the errors that are being generated aren't particularly insightful yet, they are basically staking their claim on only processing and caching images that are not streams (and inherently not null -- i.e., directories).  To find your way around this, I'm guessing it makes more sense to be explicit.  I'm thinking google/web-starter-kit#636 is a safe solution for the moment.  (Drop the things that are not files from the image caching and processing pipeline -- it just makes sense, though it doesn't excuse the other weirdness.)

**Comment by shinnn** [comment]
Fixed in https://github.com/jgable/gulp-cache/pull/43

**Comment by levivm** [comment]
@tuler Thx, I ran into same problem, I removed $.cache and it works.
