### ISSUE TITLE
Refusing to install gulp-imagemin as a dependency of itself

### ISSUE THREAD

**Issue by gweatherson** [sindresorhus/gulp-imagemin#7]
Any idea what's causing this?

$ npm install --save-dev gulp-imagemin
npm WARN package.json gulp-imagemin@0.1.4 No README data
npm WARN install Refusing to install gulp-imagemin as a dependency of itself

**Comment by agrosu** [comment]
name in package.json should be different from packages what you want to add. Try to add unique name for package.

**Comment by LoicGoyet** [comment]
@roopeshreddy thanks !

**Comment by Techaray** [comment]
Thanks for solution @roopeshreddy  when I renamed it worked well

**Comment by ilmoralito** [comment]
@roopeshreddy  Thanks man

**Comment by Swapnilniwane91** [comment]
is there any idea regarding this error

npm WARN install Refusing to install simple-odata-server as a dependency of itself

**Comment by ipavlyk** [comment]
@roopeshreddy Thanks man

**Comment by yves-s** [comment]
Thanks @jameshoward I did the same mistake to name the project the same as the dependencies name.

**Comment by WillYuSir** [comment]
@roopeshreddy yes thanks

**Comment by huangyanxiong01** [comment]
@roopeshreddy  非常感谢

**Comment by sunkuiwei** [comment]
@roopeshreddy  Thanks man

**Comment by RomanJSKA** [comment]
@roopeshreddy  THANKS!!!

**Comment by s9eb** [comment]
@roopeshreddy Thx man ! :)

**Comment by dpasby** [comment]
Thanks ~ 
:)

**Comment by MaxTan** [comment]
@roopeshreddy thanks

**Comment by dalareo** [comment]
@roopeshreddy thanks! that was the point!

**Comment by IvAndreevich** [comment]
@roopeshreddy yes, it helped! thanks a lot!
