### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by SamPotts** [sindresorhus/gulp-imagemin#88]
I'm trying to compress a load of horribly bloated illustrator SVGs and am getting the above error. 

Here's an example file:
http://cl.ly/Z9i8

**Comment by kevva** [comment]
https://github.com/imagemin/imagemin-svgo. The SVG is probably corrupt.

**Comment by SamPotts** [comment]
Did you check that file I linked? It renders fine it just seems that the SVGO isn't great at dealing with the illustrator bloat.

**Comment by kevva** [comment]
Yeah, but we don't maintain svgo. Open an issue over at https://github.com/svg/svgo. I've fixed so that it doesn't try replacing empty data.
