### ISSUE TITLE
Bundled plugins

### ISSUE THREAD

**Issue by VladShcherbin** [sindresorhus/gulp-imagemin#89]
Hello, I've installed the latest version but there is no result with the default bundles.

I've used
```
gulp.task('image', function () {
	return gulp.src('public/test/*.gif')
		.pipe(imagemin({
			progressive: true,
			interlaced: true
		}))
		.pipe(gulp.dest('public/test/ff'));
});
```
result - minified 1 image (saved 0 B)
the same is with the jpg, png.

but, if I install manually `imagemin-gifsicle` and run
```
var gifsicle = require('imagemin-gifsicle');

gulp.task('image', function () {
	return gulp.src('public/test/*.gif')
		.pipe(imagemin({
			progressive: true,
			interlaced: true,
			use: [gifsicle()]
		}))
		.pipe(gulp.dest('public/test/ff'));
});
```
the image will be minified as expected

The same is if I manually install `imagemin-jpegtran` and `use` it.

Do I have to manually download all the bundles and write them into the `use` or am I missing smth?

**Comment by kevva** [comment]
What messages are you seing upon installation? And what version are you using?

**Comment by VladShcherbin** [comment]
hm, I've uninstalled and installed again - everything is working now.
smth weird, no errors were during the first installation. maybe smth changed when I manually installed the plugins.
thanks for the advice
