### ISSUE TITLE
Installation freezes

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/gulp-imagemin#90]
When trying to install gulp-imagemin using `npm install gulp-imagemin --save-dev --save-exact` in Ubuntu 14.04 I get this far and then it just freezes and brings my computer to a halt and I have to kill the process. It's new hardware so i'm not sure what the problem is. Tried installing several times and it's always the same problem. Am I supposed to install something else first manually?

```
> jpegtran-bin@2.0.2 postinstall /project/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@2.0.4 postinstall /project/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js
```

**Comment by kevva** [comment]
Does `optipng --version` give you something?

**Comment by rightaway** [comment]
No, it doesn't look like it is installed. And when doing 'npm list' I see this after the failed installation attempt of gulp-imagemin. Do I need to install some things before gulp-imagemin separately like optipng or imagemin?

`├── gulp-imagemin@2.1.0 extraneous`

**Comment by kevva** [comment]
No, it should work out of the box.
