### ISSUE TITLE
Error: Cannot find module 'imagemin-pngquant'

### ISSUE THREAD

**Issue by jarvismartin** [sindresorhus/gulp-imagemin#91]
I know all the imagemin modules are included in this package, but to get things working, I ran 'npm install imagemin-pngquant', which seems pretty ridiculous. Is there something obvious I'm missing?
I also got it working by using the full path to the module in the require statement, but this just doesn't seem to be the way things should work...
 
    var pngquant = require('gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant');

I basically just cut and pasted the example code...

    var imagemin = require('gulp-imagemin');
    var pngquant = require('imagemin-pngquant');
    gulp.task('default', function () {
        return gulp.src('src/images/*')
            .pipe(imagemin({
                progressive: true,
                svgoPlugins: [{removeViewBox: false}],
                use: [pngquant()]
            }))
            .pipe(gulp.dest('dist'));
    });

into a project that already works ( https://github.com/jarvismartin/generator-react-material-ui ).
Thanks for all your work, and sorry to potentially add more for you to deal with. I will try to make some time later to dig into your code and see where to address this. I'm sure you guys could do this in a fraction of the time, though.
Cheers.

**Comment by sindresorhus** [comment]
> I know all the imagemin modules are included in this package

Nope. From the readme:

> Comes bundled with the following optimizers:

> gifsicle — Compress GIF images
> jpegtran — Compress JPEG images
> optipng — Compress PNG images
> svgo — Compress SVG images

> var pngquant = require('gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant');

`imagemin` bundles the `pngquant` plugin. gulp-imagemin does not.

> Is there something obvious I'm missing?

Yes. How node works. If you see a `require` statement with a module name you need to install that module from npm.

-

So is it working after `npm install`ing the plugin?

**Comment by jarvismartin** [comment]
Hey, Sindre!
Thanks a lot for your quick response! 

So, as I said already, ```npm install imagemin-pngquant``` works, and 
```var pngquant = require('gulp-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant');``` 
also works.

I guess what I'm confused about is why would I want to ```npm install``` the same modules again when they are already in this package? At the moment, I'm using the second solution above, with the long require statement. It's not the end of the world, it just seems clunky and inelegant. It does seem better than installing the same modules again, though.

Anyway, thanks again for your time and all the goodies you make available for the rest of us!
Cheers!

**Comment by kevva** [comment]
Glad it worked.

**Comment by sindresorhus** [comment]
> I guess what I'm confused about is why would I want to npm install the same modules again when they are already in this package?

It's not in this package. It's in the package this package depends on.

> I'm using the second solution above, with the long require statement. It's not the end of the world, it just seems clunky and inelegant.

That long require path will definitely break at some point. I might be crazy, but using a fragile very long require statement is my definition of clunky and inelegant.

Not sure why you've gotten this idea that separation of concern is so inelegant, but you have to realize dependencies are cheap in Node.

-

I can't remember why `imagemin` bundles pngquant, but I didn't want to.

**Comment by kevva** [comment]
Me neither tbh but I remember having a discussion about it, yeah.

**Comment by jarvismartin** [comment]
Hey, thanks, guys! I think I understand and follow what you're saying now.
I should npm install the stuff I want.
e.g.  ```npm install imagemin-pngquant```
Thanks for taking the time to explain this. I really appreciate it. 
Cheers.

**Comment by sindresorhus** [comment]
Exactly :)
