### ISSUE TITLE
imagemin-pngquant required but not documented

### ISSUE THREAD

**Issue by una** [sindresorhus/gulp-imagemin#94]
I had to install imagemin-pngquant separately to get this to run, but its not specifically documented anywhere.

**Comment by sindresorhus** [comment]
Anything you `require` you have to install. Not going to document how Node works, that's better left up to the Node docs.

**Comment by una** [comment]
Yeah and that should be documented for people who don't know that. Why wouldn't you make something easier to understand and use?

**Comment by sindresorhus** [comment]
That's not for us to document. It's how Node works. We don't document how JavaScript works either.
