### ISSUE TITLE
gulp-gm and gulp-imagemin not working together on ubuntu

### ISSUE THREAD

**Issue by callumacrae** [sindresorhus/gulp-imagemin#96]
I have no idea where to open this issue, but it's been stumping us for the best part of two days now and we're still not really sure where the error comes from.

The following runs fine on OS X, but fails on Ubuntu (and heroku, where we deploy to):

```js
var gm = require('gulp-gm');
var imagemin = require('gulp-imagemin');

gulp.task('repro', function() {
 gulp.src('./src/components/gallery/**/*.{png,jpg,gif}')
       .pipe(gm(function(gmfile) { return gmfile; }, { imageMagick: true }))
       .pipe(imagemin());
});
```

This is the error:

```js
events.js:72
       throw er; // Unhandled 'error' event
             ^
TypeError: First argument needs to be a number, array or string.
   at new Buffer (buffer.js:188:15)
   at /home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/index.js:37:16
   at /home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:32:13
   at Object.sax.onerror (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:120:9)
   at emit (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:615:33)
   at error (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:644:3)
   at strictFail (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:662:22)
   at Object.write (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/sax/lib/sax.js:935:11)
   at module.exports (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/svg2js.js:131:9)
   at SVGO.optimize (/home/vagrant/eagle/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo.js:29:5)
```

The error doesn't happen when we take gulp-gm out. gulp-debug isn't reporting anything unusual happening to the filename: I have no idea why it is being sent to the svgo plugin.

The vagrant box we were using: https://vagrantcloud.com/lazygray/boxes/heroku-cedar-14

I'm not sure if it happens on plain ubuntu. It definitely doesn't happen on OS X.

Some version info:

```
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

gulp 3.8.11
gulp-imagemin 2.2.0
gulp-gm 0.0.7
```

Here's a repo containing instructions to replicate: https://github.com/urbanautomaton/imagemin-bug

Also mentioning @scalableminds who maintains gulp-gm—I don't know if it's an issue there or here (or in gm or imagemin themselves).

**Comment by kevva** [comment]
Sounds weird. imagemin-svgo shouldn't run at all since there are no svg files.

**Comment by callumacrae** [comment]
`file.path` is equal to `undefined` in imagemin-svgo/index.js: not sure if that is relevant, but it could be why it's going to the svgo plugin.

**Comment by kevva** [comment]
Sounds like the issue is coming from `gulp-gm`. Going to have a look at it.

**Comment by callumacrae** [comment]
That's what I thought, but `gulp-debug` says that there's a file there. I'm out of my depth—thank you!

**Comment by kevva** [comment]
@sindresorhus, `is-svg` thinks it's a SVG file. Pretty weird.

**Comment by kevva** [comment]
@callumacrae, this is only happening when using ImageMagick.

**Comment by urbanautomaton** [comment]
Hi @kevva - thanks very much for looking into this for us, it's really appreciated.

We've only tried it with imagemagick (graphicsmagick isn't on heroku build boxes that I'm aware of), and it only happens with certain (rare) files. It also seems to vary depending on the imagemagick version - with 6.9.0-3 on my mac, the conversion proceeds happily, but with 6.7.7 on the vagrant (and heroku) boxes, it fails.

So it looks like particular versions of imagemagick spit out a converted version of this file that happens to have a byte sequence that `is-svg`'s regexp matches.

Obviously it would be great to fix the svg detection, but in the short term the task we're writing doesn't actually feature any svgs. Is there any way for us to remove the svgo plugin from the pipeline so that svg isn't even considered?

**Comment by callumacrae** [comment]
Perhaps `is-svg` should use something like [is-binary](https://github.com/alessioalex/is-binary) to test whether the input is binary? It doesn't seem inconceivable that there are other possible combinations of random characters that contain `<svg ... >`!

**Comment by kevva** [comment]
That's going to be hard with the current gulp-imagemin API. Best bet is to use the imagemin-plugins individually. Check the [usage](https://github.com/imagemin/imagemin-jpegtran#usage) section (second example).

**Comment by sindresorhus** [comment]
Should be fixed in `is-svg`. Try reinstalling.

**Comment by callumacrae** [comment]
Fixed! :confetti_ball: 

![](http://media.giphy.com/media/AeWoyE3ZT90YM/giphy.gif)
