### ISSUE TITLE
trojan/malware

### ISSUE THREAD

**Issue by stevo-knievo** [sindresorhus/gulp-imagemin#97]
I installed this package on my windows machine and was notified (360 total security) of trojan/malware.

Detected and intercepted Trojan attacks.

Program:    D:\Development\Projektes\agent\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\vendor\pngquant.exe

Name: HEUR/QVM20.1.Malware.Gen

**Comment by kevva** [comment]
https://github.com/imagemin/pngquant-bin/issues/25

**Comment by stevo-knievo** [comment]
I don't know but I had the version 2.1.0 installed. I switch to 2.2.0 but it is the same:

Detected and intercepted Trojan attacks.

Program:    D:\Development\Projektes\agent\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\vendor\pngquant.exe

Name: HEUR/QVM20.1.Malware.Gen

**Comment by kevva** [comment]
cc @pornel, do you have any idea why this happens?

**Comment by kevva** [comment]
cc @pornel, do you have any idea why this happens?

**Comment by pornel** [comment]
My guess is that these "total" antivirus programs are lame and have massively amplified false positive rate. 

If you run a ton of *heuristic*-based engines on an executable you're bound to find something.
