### ISSUE TITLE
Why gulp-imagemin output changed from similar grunt plugin?

### ISSUE THREAD

**Issue by Vargentum** [sindresorhus/gulp-imagemin#99]
Now I'm using gulp-imagemin, but it's minify only 5-15% from original image.
When I worked with grunt-contrib-imagemin plugin, it was minified about 50%-70% of original image size.
They both use the same imagemin library, and config options are the same.
Here the output from grunt-contrib-imagemin:
```
Running "imagemin:test" (imagemin) task
Verifying property imagemin.test exists in config...OK
Files: ./src/images/test_02.png -> ./assets/img/grunt-output/
Options: interlaced, optimizationLevel=3, progressive
✔ ./src/images/test_02.png (saved 16.89 kB - 53%)
Minified 1 image (saved 16.89 kB)
```

And it's gulp-imagemin output:
```
[13:32:43] Starting 'imagemin'...
[13:32:46] imgmin src/images/test_02.png
[13:32:46] gulp-imagemin: Minified 1 image (saved 4.03 kB - 12.7%)
[13:32:46] imgmin 1 items
[13:32:46] Finished 'imagemin' after 3.61 s
```

 Can you highlight me about this?

**Comment by kevva** [comment]
What version of the grunt plugin are you running? Until very recently it used pngquant which this plugin doesn't. I think the difference in compressed size might come from that.

**Comment by Vargentum** [comment]
Thanks, it's works.
